/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Message,
  SmsHistoriesPublic,
  SmsHistoryCreate,
  SmsHistoryPublic,
  SmsHistoryUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageFromJSON,
    MessageToJSON,
    SmsHistoriesPublicFromJSON,
    SmsHistoriesPublicToJSON,
    SmsHistoryCreateFromJSON,
    SmsHistoryCreateToJSON,
    SmsHistoryPublicFromJSON,
    SmsHistoryPublicToJSON,
    SmsHistoryUpdateFromJSON,
    SmsHistoryUpdateToJSON,
} from '../models/index';

export interface HistorysmsCreateSmsHistoryRequest {
    smsHistoryCreate: SmsHistoryCreate;
}

export interface HistorysmsDeleteSmsHistoryRequest {
    historyId: string;
}

export interface HistorysmsGetSmsHistoryRequest {
    historyId: string;
}

export interface HistorysmsListAllSmsHistoryRequest {
    skip?: number;
    limit?: number;
    status?: string | null;
    deliveryStatus?: string | null;
}

export interface HistorysmsListMySmsHistoryRequest {
    skip?: number;
    limit?: number;
    status?: string | null;
    deliveryStatus?: string | null;
}

export interface HistorysmsUpdateSmsHistoryRequest {
    historyId: string;
    smsHistoryUpdate: SmsHistoryUpdate;
}

/**
 * HistorysmsApi - interface
 * 
 * @export
 * @interface HistorysmsApiInterface
 */
export interface HistorysmsApiInterface {
    /**
     * 
     * @summary Create Sms History
     * @param {SmsHistoryCreate} smsHistoryCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistorysmsApiInterface
     */
    historysmsCreateSmsHistoryRaw(requestParameters: HistorysmsCreateSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoryPublic>>;

    /**
     * Create Sms History
     */
    historysmsCreateSmsHistory(requestParameters: HistorysmsCreateSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoryPublic>;

    /**
     * 
     * @summary Delete Sms History
     * @param {string} historyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistorysmsApiInterface
     */
    historysmsDeleteSmsHistoryRaw(requestParameters: HistorysmsDeleteSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>>;

    /**
     * Delete Sms History
     */
    historysmsDeleteSmsHistory(requestParameters: HistorysmsDeleteSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message>;

    /**
     * 
     * @summary Get Sms History
     * @param {string} historyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistorysmsApiInterface
     */
    historysmsGetSmsHistoryRaw(requestParameters: HistorysmsGetSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoryPublic>>;

    /**
     * Get Sms History
     */
    historysmsGetSmsHistory(requestParameters: HistorysmsGetSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoryPublic>;

    /**
     * 
     * @summary List All Sms History
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {string} [status] 
     * @param {string} [deliveryStatus] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistorysmsApiInterface
     */
    historysmsListAllSmsHistoryRaw(requestParameters: HistorysmsListAllSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoriesPublic>>;

    /**
     * List All Sms History
     */
    historysmsListAllSmsHistory(requestParameters: HistorysmsListAllSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoriesPublic>;

    /**
     * 
     * @summary List My Sms History
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {string} [status] 
     * @param {string} [deliveryStatus] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistorysmsApiInterface
     */
    historysmsListMySmsHistoryRaw(requestParameters: HistorysmsListMySmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoriesPublic>>;

    /**
     * List My Sms History
     */
    historysmsListMySmsHistory(requestParameters: HistorysmsListMySmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoriesPublic>;

    /**
     * 
     * @summary Sms History Stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistorysmsApiInterface
     */
    historysmsSmsHistoryStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Sms History Stats
     */
    historysmsSmsHistoryStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * 
     * @summary Update Sms History
     * @param {string} historyId 
     * @param {SmsHistoryUpdate} smsHistoryUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistorysmsApiInterface
     */
    historysmsUpdateSmsHistoryRaw(requestParameters: HistorysmsUpdateSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoryPublic>>;

    /**
     * Update Sms History
     */
    historysmsUpdateSmsHistory(requestParameters: HistorysmsUpdateSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoryPublic>;

}

/**
 * 
 */
export class HistorysmsApi extends runtime.BaseAPI implements HistorysmsApiInterface {

    /**
     * Create Sms History
     */
    async historysmsCreateSmsHistoryRaw(requestParameters: HistorysmsCreateSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoryPublic>> {
        if (requestParameters['smsHistoryCreate'] == null) {
            throw new runtime.RequiredError(
                'smsHistoryCreate',
                'Required parameter "smsHistoryCreate" was null or undefined when calling historysmsCreateSmsHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/historysms/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SmsHistoryCreateToJSON(requestParameters['smsHistoryCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmsHistoryPublicFromJSON(jsonValue));
    }

    /**
     * Create Sms History
     */
    async historysmsCreateSmsHistory(requestParameters: HistorysmsCreateSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoryPublic> {
        const response = await this.historysmsCreateSmsHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Sms History
     */
    async historysmsDeleteSmsHistoryRaw(requestParameters: HistorysmsDeleteSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        if (requestParameters['historyId'] == null) {
            throw new runtime.RequiredError(
                'historyId',
                'Required parameter "historyId" was null or undefined when calling historysmsDeleteSmsHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/historysms/{history_id}`;
        urlPath = urlPath.replace(`{${"history_id"}}`, encodeURIComponent(String(requestParameters['historyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Delete Sms History
     */
    async historysmsDeleteSmsHistory(requestParameters: HistorysmsDeleteSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.historysmsDeleteSmsHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Sms History
     */
    async historysmsGetSmsHistoryRaw(requestParameters: HistorysmsGetSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoryPublic>> {
        if (requestParameters['historyId'] == null) {
            throw new runtime.RequiredError(
                'historyId',
                'Required parameter "historyId" was null or undefined when calling historysmsGetSmsHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/historysms/{history_id}`;
        urlPath = urlPath.replace(`{${"history_id"}}`, encodeURIComponent(String(requestParameters['historyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmsHistoryPublicFromJSON(jsonValue));
    }

    /**
     * Get Sms History
     */
    async historysmsGetSmsHistory(requestParameters: HistorysmsGetSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoryPublic> {
        const response = await this.historysmsGetSmsHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List All Sms History
     */
    async historysmsListAllSmsHistoryRaw(requestParameters: HistorysmsListAllSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoriesPublic>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['deliveryStatus'] != null) {
            queryParameters['delivery_status'] = requestParameters['deliveryStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/historysms/all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmsHistoriesPublicFromJSON(jsonValue));
    }

    /**
     * List All Sms History
     */
    async historysmsListAllSmsHistory(requestParameters: HistorysmsListAllSmsHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoriesPublic> {
        const response = await this.historysmsListAllSmsHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List My Sms History
     */
    async historysmsListMySmsHistoryRaw(requestParameters: HistorysmsListMySmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoriesPublic>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['deliveryStatus'] != null) {
            queryParameters['delivery_status'] = requestParameters['deliveryStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/historysms/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmsHistoriesPublicFromJSON(jsonValue));
    }

    /**
     * List My Sms History
     */
    async historysmsListMySmsHistory(requestParameters: HistorysmsListMySmsHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoriesPublic> {
        const response = await this.historysmsListMySmsHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sms History Stats
     */
    async historysmsSmsHistoryStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/historysms/stats/summary`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Sms History Stats
     */
    async historysmsSmsHistoryStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.historysmsSmsHistoryStatsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Sms History
     */
    async historysmsUpdateSmsHistoryRaw(requestParameters: HistorysmsUpdateSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsHistoryPublic>> {
        if (requestParameters['historyId'] == null) {
            throw new runtime.RequiredError(
                'historyId',
                'Required parameter "historyId" was null or undefined when calling historysmsUpdateSmsHistory().'
            );
        }

        if (requestParameters['smsHistoryUpdate'] == null) {
            throw new runtime.RequiredError(
                'smsHistoryUpdate',
                'Required parameter "smsHistoryUpdate" was null or undefined when calling historysmsUpdateSmsHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/historysms/{history_id}`;
        urlPath = urlPath.replace(`{${"history_id"}}`, encodeURIComponent(String(requestParameters['historyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SmsHistoryUpdateToJSON(requestParameters['smsHistoryUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmsHistoryPublicFromJSON(jsonValue));
    }

    /**
     * Update Sms History
     */
    async historysmsUpdateSmsHistory(requestParameters: HistorysmsUpdateSmsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsHistoryPublic> {
        const response = await this.historysmsUpdateSmsHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
