/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddBalanceRequest,
  ApiKeyPublic,
  BulkTemplateCreate,
  HTTPValidationError,
  Message,
  SystemStats,
  TemplatePublic,
  TicketPublic,
  TransactionPublic,
  UserActivityLog,
  UserDetailedInfo,
  UserSearchResult,
} from '../models/index';
import {
    AddBalanceRequestFromJSON,
    AddBalanceRequestToJSON,
    ApiKeyPublicFromJSON,
    ApiKeyPublicToJSON,
    BulkTemplateCreateFromJSON,
    BulkTemplateCreateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageFromJSON,
    MessageToJSON,
    SystemStatsFromJSON,
    SystemStatsToJSON,
    TemplatePublicFromJSON,
    TemplatePublicToJSON,
    TicketPublicFromJSON,
    TicketPublicToJSON,
    TransactionPublicFromJSON,
    TransactionPublicToJSON,
    UserActivityLogFromJSON,
    UserActivityLogToJSON,
    UserDetailedInfoFromJSON,
    UserDetailedInfoToJSON,
    UserSearchResultFromJSON,
    UserSearchResultToJSON,
} from '../models/index';

export interface MoreAdminPrivilegesActivateUserRequest {
    userId: string;
}

export interface MoreAdminPrivilegesAddBalanceToUserRequest {
    userId: string;
    addBalanceRequest: AddBalanceRequest;
}

export interface MoreAdminPrivilegesAssignTicketRequest {
    ticketId: string;
    assignedTo: string;
}

export interface MoreAdminPrivilegesBulkUpdateUserPlanRequest {
    newPlan: string;
    requestBody: Array<string>;
}

export interface MoreAdminPrivilegesCreatePrebuiltTemplateRequest {
    bulkTemplateCreate: BulkTemplateCreate;
}

export interface MoreAdminPrivilegesDeactivateUserRequest {
    userId: string;
}

export interface MoreAdminPrivilegesGetAllTicketsRequest {
    status?: string | null;
    priority?: string | null;
    assignedToMe?: boolean;
    skip?: number;
    limit?: number;
}

export interface MoreAdminPrivilegesGetSmsAnalyticsRequest {
    days?: number;
}

export interface MoreAdminPrivilegesGetTransactionAnalyticsRequest {
    days?: number;
}

export interface MoreAdminPrivilegesGetUserActivityLogsRequest {
    userId: string;
    activityType?: string | null;
    days?: number;
    skip?: number;
    limit?: number;
}

export interface MoreAdminPrivilegesGetUserApiKeysRequest {
    userId: string;
    isActive?: boolean | null;
}

export interface MoreAdminPrivilegesGetUserDetailedInfoRequest {
    userId: string;
}

export interface MoreAdminPrivilegesGetUserTicketsRequest {
    userId: string;
    status?: string | null;
    priority?: string | null;
    skip?: number;
    limit?: number;
}

export interface MoreAdminPrivilegesListPrebuiltTemplatesRequest {
    skip?: number;
    limit?: number;
}

export interface MoreAdminPrivilegesRevokeApiKeyRequest {
    userId: string;
    keyId: string;
}

export interface MoreAdminPrivilegesSearchUsersRequest {
    query?: string | null;
    plan?: string | null;
    isActive?: boolean | null;
    skip?: number;
    limit?: number;
}

/**
 * MoreAdminPrivilegesApi - interface
 * 
 * @export
 * @interface MoreAdminPrivilegesApiInterface
 */
export interface MoreAdminPrivilegesApiInterface {
    /**
     * Activate a user account. Uses indexed primary key lookup.
     * @summary Activate User
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesActivateUserRaw(requestParameters: MoreAdminPrivilegesActivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>>;

    /**
     * Activate a user account. Uses indexed primary key lookup.
     * Activate User
     */
    moreAdminPrivilegesActivateUser(requestParameters: MoreAdminPrivilegesActivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message>;

    /**
     * Add balance to user account with transaction tracking. Uses indexed user_id for fast lookup and creates audit trail. Background task recalculates user metrics for consistency.
     * @summary Add Balance To User
     * @param {string} userId 
     * @param {AddBalanceRequest} addBalanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesAddBalanceToUserRaw(requestParameters: MoreAdminPrivilegesAddBalanceToUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPublic>>;

    /**
     * Add balance to user account with transaction tracking. Uses indexed user_id for fast lookup and creates audit trail. Background task recalculates user metrics for consistency.
     * Add Balance To User
     */
    moreAdminPrivilegesAddBalanceToUser(requestParameters: MoreAdminPrivilegesAddBalanceToUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPublic>;

    /**
     * Assign a ticket to a support agent. Uses indexed primary key lookups.
     * @summary Assign Ticket
     * @param {string} ticketId 
     * @param {string} assignedTo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesAssignTicketRaw(requestParameters: MoreAdminPrivilegesAssignTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketPublic>>;

    /**
     * Assign a ticket to a support agent. Uses indexed primary key lookups.
     * Assign Ticket
     */
    moreAdminPrivilegesAssignTicket(requestParameters: MoreAdminPrivilegesAssignTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketPublic>;

    /**
     * Bulk update user plans with optimized batch query. Uses indexed user_id for efficient updates. Automatically updates SMS cost based on the new plan.
     * @summary Bulk Update User Plan
     * @param {string} newPlan 
     * @param {Array<string>} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesBulkUpdateUserPlanRaw(requestParameters: MoreAdminPrivilegesBulkUpdateUserPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>>;

    /**
     * Bulk update user plans with optimized batch query. Uses indexed user_id for efficient updates. Automatically updates SMS cost based on the new plan.
     * Bulk Update User Plan
     */
    moreAdminPrivilegesBulkUpdateUserPlan(requestParameters: MoreAdminPrivilegesBulkUpdateUserPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message>;

    /**
     * Create prebuilt templates that are displayed to all users. These templates have default=True and are owned by admin. Uses indexed owner_id for efficient template queries.
     * @summary Create Prebuilt Template
     * @param {BulkTemplateCreate} bulkTemplateCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesCreatePrebuiltTemplateRaw(requestParameters: MoreAdminPrivilegesCreatePrebuiltTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>>;

    /**
     * Create prebuilt templates that are displayed to all users. These templates have default=True and are owned by admin. Uses indexed owner_id for efficient template queries.
     * Create Prebuilt Template
     */
    moreAdminPrivilegesCreatePrebuiltTemplate(requestParameters: MoreAdminPrivilegesCreatePrebuiltTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic>;

    /**
     * Deactivate a user account. Uses indexed primary key lookup.
     * @summary Deactivate User
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesDeactivateUserRaw(requestParameters: MoreAdminPrivilegesDeactivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>>;

    /**
     * Deactivate a user account. Uses indexed primary key lookup.
     * Deactivate User
     */
    moreAdminPrivilegesDeactivateUser(requestParameters: MoreAdminPrivilegesDeactivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message>;

    /**
     * Get all tickets in the system with advanced filtering. Optimized with indexed queries on status, priority, and created_at.
     * @summary Get All Tickets
     * @param {string} [status] Filter by status
     * @param {string} [priority] Filter by priority
     * @param {boolean} [assignedToMe] Show only tickets assigned to me
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetAllTicketsRaw(requestParameters: MoreAdminPrivilegesGetAllTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketPublic>>>;

    /**
     * Get all tickets in the system with advanced filtering. Optimized with indexed queries on status, priority, and created_at.
     * Get All Tickets
     */
    moreAdminPrivilegesGetAllTickets(requestParameters: MoreAdminPrivilegesGetAllTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketPublic>>;

    /**
     * Get SMS analytics and statistics. Uses aggregated queries with indexed fields for performance.
     * @summary Get Sms Analytics
     * @param {number} [days] Number of days to analyze
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetSmsAnalyticsRaw(requestParameters: MoreAdminPrivilegesGetSmsAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Get SMS analytics and statistics. Uses aggregated queries with indexed fields for performance.
     * Get Sms Analytics
     */
    moreAdminPrivilegesGetSmsAnalytics(requestParameters: MoreAdminPrivilegesGetSmsAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Get system-wide statistics with optimized aggregation queries. Uses database-level aggregations for performance. All queries use indexed fields for fast execution.
     * @summary Get System Statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetSystemStatisticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemStats>>;

    /**
     * Get system-wide statistics with optimized aggregation queries. Uses database-level aggregations for performance. All queries use indexed fields for fast execution.
     * Get System Statistics
     */
    moreAdminPrivilegesGetSystemStatistics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemStats>;

    /**
     * Get transaction analytics and revenue statistics. Uses optimized aggregation queries with indexed fields.
     * @summary Get Transaction Analytics
     * @param {number} [days] Number of days to analyze
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetTransactionAnalyticsRaw(requestParameters: MoreAdminPrivilegesGetTransactionAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Get transaction analytics and revenue statistics. Uses optimized aggregation queries with indexed fields.
     * Get Transaction Analytics
     */
    moreAdminPrivilegesGetTransactionAnalytics(requestParameters: MoreAdminPrivilegesGetTransactionAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Get user activity logs from multiple sources. Aggregates data from transactions, SMS history, and tickets. Uses indexed created_at fields for efficient time-based queries.
     * @summary Get User Activity Logs
     * @param {string} userId 
     * @param {string} [activityType] Filter by activity type
     * @param {number} [days] Number of days to look back
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetUserActivityLogsRaw(requestParameters: MoreAdminPrivilegesGetUserActivityLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserActivityLog>>>;

    /**
     * Get user activity logs from multiple sources. Aggregates data from transactions, SMS history, and tickets. Uses indexed created_at fields for efficient time-based queries.
     * Get User Activity Logs
     */
    moreAdminPrivilegesGetUserActivityLogs(requestParameters: MoreAdminPrivilegesGetUserActivityLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserActivityLog>>;

    /**
     * Get all API keys for a specific user. Uses indexed user_id for efficient lookup.
     * @summary Get User Api Keys
     * @param {string} userId 
     * @param {boolean} [isActive] Filter by active status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetUserApiKeysRaw(requestParameters: MoreAdminPrivilegesGetUserApiKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiKeyPublic>>>;

    /**
     * Get all API keys for a specific user. Uses indexed user_id for efficient lookup.
     * Get User Api Keys
     */
    moreAdminPrivilegesGetUserApiKeys(requestParameters: MoreAdminPrivilegesGetUserApiKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiKeyPublic>>;

    /**
     * Get comprehensive user information with all related data. Uses optimized joins and aggregations for performance. Indexes on user_id foreign keys ensure fast lookups.
     * @summary Get User Detailed Info
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetUserDetailedInfoRaw(requestParameters: MoreAdminPrivilegesGetUserDetailedInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetailedInfo>>;

    /**
     * Get comprehensive user information with all related data. Uses optimized joins and aggregations for performance. Indexes on user_id foreign keys ensure fast lookups.
     * Get User Detailed Info
     */
    moreAdminPrivilegesGetUserDetailedInfo(requestParameters: MoreAdminPrivilegesGetUserDetailedInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetailedInfo>;

    /**
     * Get user engagement metrics. Uses optimized queries with indexed fields.
     * @summary Get User Engagement Metrics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetUserEngagementMetricsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Get user engagement metrics. Uses optimized queries with indexed fields.
     * Get User Engagement Metrics
     */
    moreAdminPrivilegesGetUserEngagementMetrics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Get all tickets for a specific user with filtering. Uses indexed user_id and created_at for efficient queries. Supports filtering by status and priority.
     * @summary Get User Tickets
     * @param {string} userId 
     * @param {string} [status] Filter by ticket status
     * @param {string} [priority] Filter by priority
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesGetUserTicketsRaw(requestParameters: MoreAdminPrivilegesGetUserTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketPublic>>>;

    /**
     * Get all tickets for a specific user with filtering. Uses indexed user_id and created_at for efficient queries. Supports filtering by status and priority.
     * Get User Tickets
     */
    moreAdminPrivilegesGetUserTickets(requestParameters: MoreAdminPrivilegesGetUserTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketPublic>>;

    /**
     * List all prebuilt templates. Uses indexed query on default flag for optimization.
     * @summary List Prebuilt Templates
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesListPrebuiltTemplatesRaw(requestParameters: MoreAdminPrivilegesListPrebuiltTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TemplatePublic>>>;

    /**
     * List all prebuilt templates. Uses indexed query on default flag for optimization.
     * List Prebuilt Templates
     */
    moreAdminPrivilegesListPrebuiltTemplates(requestParameters: MoreAdminPrivilegesListPrebuiltTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TemplatePublic>>;

    /**
     * Revoke a user\'s API key. Uses indexed primary key lookup.
     * @summary Revoke Api Key
     * @param {string} userId 
     * @param {string} keyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesRevokeApiKeyRaw(requestParameters: MoreAdminPrivilegesRevokeApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>>;

    /**
     * Revoke a user\'s API key. Uses indexed primary key lookup.
     * Revoke Api Key
     */
    moreAdminPrivilegesRevokeApiKey(requestParameters: MoreAdminPrivilegesRevokeApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message>;

    /**
     * Search users with optimized query using indexing. Supports filtering by email, name, plan, and active status. Uses database indexes on email and user_id for fast lookups.
     * @summary Search Users
     * @param {string} [query] Search by email, name, or ID
     * @param {string} [plan] Filter by plan subscription
     * @param {boolean} [isActive] Filter by active status
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoreAdminPrivilegesApiInterface
     */
    moreAdminPrivilegesSearchUsersRaw(requestParameters: MoreAdminPrivilegesSearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserSearchResult>>>;

    /**
     * Search users with optimized query using indexing. Supports filtering by email, name, plan, and active status. Uses database indexes on email and user_id for fast lookups.
     * Search Users
     */
    moreAdminPrivilegesSearchUsers(requestParameters: MoreAdminPrivilegesSearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserSearchResult>>;

}

/**
 * 
 */
export class MoreAdminPrivilegesApi extends runtime.BaseAPI implements MoreAdminPrivilegesApiInterface {

    /**
     * Activate a user account. Uses indexed primary key lookup.
     * Activate User
     */
    async moreAdminPrivilegesActivateUserRaw(requestParameters: MoreAdminPrivilegesActivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling moreAdminPrivilegesActivateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/{user_id}/activate`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Activate a user account. Uses indexed primary key lookup.
     * Activate User
     */
    async moreAdminPrivilegesActivateUser(requestParameters: MoreAdminPrivilegesActivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.moreAdminPrivilegesActivateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add balance to user account with transaction tracking. Uses indexed user_id for fast lookup and creates audit trail. Background task recalculates user metrics for consistency.
     * Add Balance To User
     */
    async moreAdminPrivilegesAddBalanceToUserRaw(requestParameters: MoreAdminPrivilegesAddBalanceToUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPublic>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling moreAdminPrivilegesAddBalanceToUser().'
            );
        }

        if (requestParameters['addBalanceRequest'] == null) {
            throw new runtime.RequiredError(
                'addBalanceRequest',
                'Required parameter "addBalanceRequest" was null or undefined when calling moreAdminPrivilegesAddBalanceToUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/{user_id}/add-balance`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddBalanceRequestToJSON(requestParameters['addBalanceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionPublicFromJSON(jsonValue));
    }

    /**
     * Add balance to user account with transaction tracking. Uses indexed user_id for fast lookup and creates audit trail. Background task recalculates user metrics for consistency.
     * Add Balance To User
     */
    async moreAdminPrivilegesAddBalanceToUser(requestParameters: MoreAdminPrivilegesAddBalanceToUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPublic> {
        const response = await this.moreAdminPrivilegesAddBalanceToUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Assign a ticket to a support agent. Uses indexed primary key lookups.
     * Assign Ticket
     */
    async moreAdminPrivilegesAssignTicketRaw(requestParameters: MoreAdminPrivilegesAssignTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketPublic>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling moreAdminPrivilegesAssignTicket().'
            );
        }

        if (requestParameters['assignedTo'] == null) {
            throw new runtime.RequiredError(
                'assignedTo',
                'Required parameter "assignedTo" was null or undefined when calling moreAdminPrivilegesAssignTicket().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['assignedTo'] != null) {
            queryParameters['assigned_to'] = requestParameters['assignedTo'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/tickets/{ticket_id}/assign`;
        urlPath = urlPath.replace(`{${"ticket_id"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketPublicFromJSON(jsonValue));
    }

    /**
     * Assign a ticket to a support agent. Uses indexed primary key lookups.
     * Assign Ticket
     */
    async moreAdminPrivilegesAssignTicket(requestParameters: MoreAdminPrivilegesAssignTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketPublic> {
        const response = await this.moreAdminPrivilegesAssignTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Bulk update user plans with optimized batch query. Uses indexed user_id for efficient updates. Automatically updates SMS cost based on the new plan.
     * Bulk Update User Plan
     */
    async moreAdminPrivilegesBulkUpdateUserPlanRaw(requestParameters: MoreAdminPrivilegesBulkUpdateUserPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        if (requestParameters['newPlan'] == null) {
            throw new runtime.RequiredError(
                'newPlan',
                'Required parameter "newPlan" was null or undefined when calling moreAdminPrivilegesBulkUpdateUserPlan().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling moreAdminPrivilegesBulkUpdateUserPlan().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['newPlan'] != null) {
            queryParameters['new_plan'] = requestParameters['newPlan'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/bulk-update-plan`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Bulk update user plans with optimized batch query. Uses indexed user_id for efficient updates. Automatically updates SMS cost based on the new plan.
     * Bulk Update User Plan
     */
    async moreAdminPrivilegesBulkUpdateUserPlan(requestParameters: MoreAdminPrivilegesBulkUpdateUserPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.moreAdminPrivilegesBulkUpdateUserPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create prebuilt templates that are displayed to all users. These templates have default=True and are owned by admin. Uses indexed owner_id for efficient template queries.
     * Create Prebuilt Template
     */
    async moreAdminPrivilegesCreatePrebuiltTemplateRaw(requestParameters: MoreAdminPrivilegesCreatePrebuiltTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>> {
        if (requestParameters['bulkTemplateCreate'] == null) {
            throw new runtime.RequiredError(
                'bulkTemplateCreate',
                'Required parameter "bulkTemplateCreate" was null or undefined when calling moreAdminPrivilegesCreatePrebuiltTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/templates/prebuilt`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkTemplateCreateToJSON(requestParameters['bulkTemplateCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatePublicFromJSON(jsonValue));
    }

    /**
     * Create prebuilt templates that are displayed to all users. These templates have default=True and are owned by admin. Uses indexed owner_id for efficient template queries.
     * Create Prebuilt Template
     */
    async moreAdminPrivilegesCreatePrebuiltTemplate(requestParameters: MoreAdminPrivilegesCreatePrebuiltTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic> {
        const response = await this.moreAdminPrivilegesCreatePrebuiltTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivate a user account. Uses indexed primary key lookup.
     * Deactivate User
     */
    async moreAdminPrivilegesDeactivateUserRaw(requestParameters: MoreAdminPrivilegesDeactivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling moreAdminPrivilegesDeactivateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/{user_id}/deactivate`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Deactivate a user account. Uses indexed primary key lookup.
     * Deactivate User
     */
    async moreAdminPrivilegesDeactivateUser(requestParameters: MoreAdminPrivilegesDeactivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.moreAdminPrivilegesDeactivateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all tickets in the system with advanced filtering. Optimized with indexed queries on status, priority, and created_at.
     * Get All Tickets
     */
    async moreAdminPrivilegesGetAllTicketsRaw(requestParameters: MoreAdminPrivilegesGetAllTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketPublic>>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['priority'] != null) {
            queryParameters['priority'] = requestParameters['priority'];
        }

        if (requestParameters['assignedToMe'] != null) {
            queryParameters['assigned_to_me'] = requestParameters['assignedToMe'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/tickets/all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketPublicFromJSON));
    }

    /**
     * Get all tickets in the system with advanced filtering. Optimized with indexed queries on status, priority, and created_at.
     * Get All Tickets
     */
    async moreAdminPrivilegesGetAllTickets(requestParameters: MoreAdminPrivilegesGetAllTicketsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketPublic>> {
        const response = await this.moreAdminPrivilegesGetAllTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get SMS analytics and statistics. Uses aggregated queries with indexed fields for performance.
     * Get Sms Analytics
     */
    async moreAdminPrivilegesGetSmsAnalyticsRaw(requestParameters: MoreAdminPrivilegesGetSmsAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        if (requestParameters['days'] != null) {
            queryParameters['days'] = requestParameters['days'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/analytics/sms-overview`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get SMS analytics and statistics. Uses aggregated queries with indexed fields for performance.
     * Get Sms Analytics
     */
    async moreAdminPrivilegesGetSmsAnalytics(requestParameters: MoreAdminPrivilegesGetSmsAnalyticsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.moreAdminPrivilegesGetSmsAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get system-wide statistics with optimized aggregation queries. Uses database-level aggregations for performance. All queries use indexed fields for fast execution.
     * Get System Statistics
     */
    async moreAdminPrivilegesGetSystemStatisticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemStats>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/system/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemStatsFromJSON(jsonValue));
    }

    /**
     * Get system-wide statistics with optimized aggregation queries. Uses database-level aggregations for performance. All queries use indexed fields for fast execution.
     * Get System Statistics
     */
    async moreAdminPrivilegesGetSystemStatistics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemStats> {
        const response = await this.moreAdminPrivilegesGetSystemStatisticsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get transaction analytics and revenue statistics. Uses optimized aggregation queries with indexed fields.
     * Get Transaction Analytics
     */
    async moreAdminPrivilegesGetTransactionAnalyticsRaw(requestParameters: MoreAdminPrivilegesGetTransactionAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        if (requestParameters['days'] != null) {
            queryParameters['days'] = requestParameters['days'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/analytics/transactions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get transaction analytics and revenue statistics. Uses optimized aggregation queries with indexed fields.
     * Get Transaction Analytics
     */
    async moreAdminPrivilegesGetTransactionAnalytics(requestParameters: MoreAdminPrivilegesGetTransactionAnalyticsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.moreAdminPrivilegesGetTransactionAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user activity logs from multiple sources. Aggregates data from transactions, SMS history, and tickets. Uses indexed created_at fields for efficient time-based queries.
     * Get User Activity Logs
     */
    async moreAdminPrivilegesGetUserActivityLogsRaw(requestParameters: MoreAdminPrivilegesGetUserActivityLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserActivityLog>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling moreAdminPrivilegesGetUserActivityLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['activityType'] != null) {
            queryParameters['activity_type'] = requestParameters['activityType'];
        }

        if (requestParameters['days'] != null) {
            queryParameters['days'] = requestParameters['days'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/{user_id}/activity-logs`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserActivityLogFromJSON));
    }

    /**
     * Get user activity logs from multiple sources. Aggregates data from transactions, SMS history, and tickets. Uses indexed created_at fields for efficient time-based queries.
     * Get User Activity Logs
     */
    async moreAdminPrivilegesGetUserActivityLogs(requestParameters: MoreAdminPrivilegesGetUserActivityLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserActivityLog>> {
        const response = await this.moreAdminPrivilegesGetUserActivityLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all API keys for a specific user. Uses indexed user_id for efficient lookup.
     * Get User Api Keys
     */
    async moreAdminPrivilegesGetUserApiKeysRaw(requestParameters: MoreAdminPrivilegesGetUserApiKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiKeyPublic>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling moreAdminPrivilegesGetUserApiKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['isActive'] != null) {
            queryParameters['is_active'] = requestParameters['isActive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/{user_id}/api-keys`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiKeyPublicFromJSON));
    }

    /**
     * Get all API keys for a specific user. Uses indexed user_id for efficient lookup.
     * Get User Api Keys
     */
    async moreAdminPrivilegesGetUserApiKeys(requestParameters: MoreAdminPrivilegesGetUserApiKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiKeyPublic>> {
        const response = await this.moreAdminPrivilegesGetUserApiKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get comprehensive user information with all related data. Uses optimized joins and aggregations for performance. Indexes on user_id foreign keys ensure fast lookups.
     * Get User Detailed Info
     */
    async moreAdminPrivilegesGetUserDetailedInfoRaw(requestParameters: MoreAdminPrivilegesGetUserDetailedInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetailedInfo>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling moreAdminPrivilegesGetUserDetailedInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/{user_id}/detailed`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDetailedInfoFromJSON(jsonValue));
    }

    /**
     * Get comprehensive user information with all related data. Uses optimized joins and aggregations for performance. Indexes on user_id foreign keys ensure fast lookups.
     * Get User Detailed Info
     */
    async moreAdminPrivilegesGetUserDetailedInfo(requestParameters: MoreAdminPrivilegesGetUserDetailedInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetailedInfo> {
        const response = await this.moreAdminPrivilegesGetUserDetailedInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user engagement metrics. Uses optimized queries with indexed fields.
     * Get User Engagement Metrics
     */
    async moreAdminPrivilegesGetUserEngagementMetricsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/analytics/user-engagement`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get user engagement metrics. Uses optimized queries with indexed fields.
     * Get User Engagement Metrics
     */
    async moreAdminPrivilegesGetUserEngagementMetrics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.moreAdminPrivilegesGetUserEngagementMetricsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all tickets for a specific user with filtering. Uses indexed user_id and created_at for efficient queries. Supports filtering by status and priority.
     * Get User Tickets
     */
    async moreAdminPrivilegesGetUserTicketsRaw(requestParameters: MoreAdminPrivilegesGetUserTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketPublic>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling moreAdminPrivilegesGetUserTickets().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['priority'] != null) {
            queryParameters['priority'] = requestParameters['priority'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/{user_id}/tickets`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketPublicFromJSON));
    }

    /**
     * Get all tickets for a specific user with filtering. Uses indexed user_id and created_at for efficient queries. Supports filtering by status and priority.
     * Get User Tickets
     */
    async moreAdminPrivilegesGetUserTickets(requestParameters: MoreAdminPrivilegesGetUserTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketPublic>> {
        const response = await this.moreAdminPrivilegesGetUserTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all prebuilt templates. Uses indexed query on default flag for optimization.
     * List Prebuilt Templates
     */
    async moreAdminPrivilegesListPrebuiltTemplatesRaw(requestParameters: MoreAdminPrivilegesListPrebuiltTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TemplatePublic>>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/templates/prebuilt`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TemplatePublicFromJSON));
    }

    /**
     * List all prebuilt templates. Uses indexed query on default flag for optimization.
     * List Prebuilt Templates
     */
    async moreAdminPrivilegesListPrebuiltTemplates(requestParameters: MoreAdminPrivilegesListPrebuiltTemplatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TemplatePublic>> {
        const response = await this.moreAdminPrivilegesListPrebuiltTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke a user\'s API key. Uses indexed primary key lookup.
     * Revoke Api Key
     */
    async moreAdminPrivilegesRevokeApiKeyRaw(requestParameters: MoreAdminPrivilegesRevokeApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling moreAdminPrivilegesRevokeApiKey().'
            );
        }

        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling moreAdminPrivilegesRevokeApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/{user_id}/api-keys/{key_id}/revoke`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Revoke a user\'s API key. Uses indexed primary key lookup.
     * Revoke Api Key
     */
    async moreAdminPrivilegesRevokeApiKey(requestParameters: MoreAdminPrivilegesRevokeApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.moreAdminPrivilegesRevokeApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search users with optimized query using indexing. Supports filtering by email, name, plan, and active status. Uses database indexes on email and user_id for fast lookups.
     * Search Users
     */
    async moreAdminPrivilegesSearchUsersRaw(requestParameters: MoreAdminPrivilegesSearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserSearchResult>>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['plan'] != null) {
            queryParameters['plan'] = requestParameters['plan'];
        }

        if (requestParameters['isActive'] != null) {
            queryParameters['is_active'] = requestParameters['isActive'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/admin/users/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserSearchResultFromJSON));
    }

    /**
     * Search users with optimized query using indexing. Supports filtering by email, name, plan, and active status. Uses database indexes on email and user_id for fast lookups.
     * Search Users
     */
    async moreAdminPrivilegesSearchUsers(requestParameters: MoreAdminPrivilegesSearchUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserSearchResult>> {
        const response = await this.moreAdminPrivilegesSearchUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
