/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApplyPromoCodeRequest,
  ApplyPromoCodeResponse,
  HTTPValidationError,
  Message,
  PromoCodeCreate,
  PromoCodePublic,
  PromoCodeUpdate,
  PromoCodesPublic,
} from '../models/index';
import {
    ApplyPromoCodeRequestFromJSON,
    ApplyPromoCodeRequestToJSON,
    ApplyPromoCodeResponseFromJSON,
    ApplyPromoCodeResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageFromJSON,
    MessageToJSON,
    PromoCodeCreateFromJSON,
    PromoCodeCreateToJSON,
    PromoCodePublicFromJSON,
    PromoCodePublicToJSON,
    PromoCodeUpdateFromJSON,
    PromoCodeUpdateToJSON,
    PromoCodesPublicFromJSON,
    PromoCodesPublicToJSON,
} from '../models/index';

export interface PromoCodesApplyPromoCodeRequest {
    applyPromoCodeRequest: ApplyPromoCodeRequest;
}

export interface PromoCodesCreatePromoCodeRequest {
    promoCodeCreate: PromoCodeCreate;
}

export interface PromoCodesDeletePromoCodeRequest {
    promoId: string;
}

export interface PromoCodesGetAllPromoCodesRequest {
    skip?: number;
    limit?: number;
    activeOnly?: boolean;
}

export interface PromoCodesGetPromoCodeRequest {
    code: string;
}

export interface PromoCodesGetPromoCodeStatsRequest {
    promoId: string;
}

export interface PromoCodesUpdatePromoCodeRequest {
    promoId: string;
    promoCodeUpdate: PromoCodeUpdate;
}

export interface PromoCodesValidatePromoCodeRequest {
    code: string;
}

/**
 * PromoCodesApi - interface
 * 
 * @export
 * @interface PromoCodesApiInterface
 */
export interface PromoCodesApiInterface {
    /**
     * Apply a promo code to get special SMS pricing. This updates the user\'s sms_cost permanently (or until another promo is applied).
     * @summary Apply Promo Code
     * @param {ApplyPromoCodeRequest} applyPromoCodeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesApplyPromoCodeRaw(requestParameters: PromoCodesApplyPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplyPromoCodeResponse>>;

    /**
     * Apply a promo code to get special SMS pricing. This updates the user\'s sms_cost permanently (or until another promo is applied).
     * Apply Promo Code
     */
    promoCodesApplyPromoCode(requestParameters: PromoCodesApplyPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplyPromoCodeResponse>;

    /**
     * Create a new promo code with special SMS pricing. (Admin only)
     * @summary Create Promo Code
     * @param {PromoCodeCreate} promoCodeCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesCreatePromoCodeRaw(requestParameters: PromoCodesCreatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoCodePublic>>;

    /**
     * Create a new promo code with special SMS pricing. (Admin only)
     * Create Promo Code
     */
    promoCodesCreatePromoCode(requestParameters: PromoCodesCreatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoCodePublic>;

    /**
     * Delete a promo code. (Admin only)
     * @summary Delete Promo Code
     * @param {string} promoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesDeletePromoCodeRaw(requestParameters: PromoCodesDeletePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>>;

    /**
     * Delete a promo code. (Admin only)
     * Delete Promo Code
     */
    promoCodesDeletePromoCode(requestParameters: PromoCodesDeletePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message>;

    /**
     * Get all promo codes. (Admin only)
     * @summary Get All Promo Codes
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {boolean} [activeOnly] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesGetAllPromoCodesRaw(requestParameters: PromoCodesGetAllPromoCodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoCodesPublic>>;

    /**
     * Get all promo codes. (Admin only)
     * Get All Promo Codes
     */
    promoCodesGetAllPromoCodes(requestParameters: PromoCodesGetAllPromoCodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoCodesPublic>;

    /**
     * Check if current user has a special promo rate applied.
     * @summary Get My Active Promo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesGetMyActivePromoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Check if current user has a special promo rate applied.
     * Get My Active Promo
     */
    promoCodesGetMyActivePromo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Get a specific promo code by code. (Admin only)
     * @summary Get Promo Code
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesGetPromoCodeRaw(requestParameters: PromoCodesGetPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoCodePublic>>;

    /**
     * Get a specific promo code by code. (Admin only)
     * Get Promo Code
     */
    promoCodesGetPromoCode(requestParameters: PromoCodesGetPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoCodePublic>;

    /**
     * Get usage statistics for a promo code. (Admin only)
     * @summary Get Promo Code Stats
     * @param {string} promoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesGetPromoCodeStatsRaw(requestParameters: PromoCodesGetPromoCodeStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Get usage statistics for a promo code. (Admin only)
     * Get Promo Code Stats
     */
    promoCodesGetPromoCodeStats(requestParameters: PromoCodesGetPromoCodeStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Update a promo code. (Admin only)
     * @summary Update Promo Code
     * @param {string} promoId 
     * @param {PromoCodeUpdate} promoCodeUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesUpdatePromoCodeRaw(requestParameters: PromoCodesUpdatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoCodePublic>>;

    /**
     * Update a promo code. (Admin only)
     * Update Promo Code
     */
    promoCodesUpdatePromoCode(requestParameters: PromoCodesUpdatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoCodePublic>;

    /**
     * Validate a promo code without applying it. Anyone can validate to see if code is valid.
     * @summary Validate Promo Code
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromoCodesApiInterface
     */
    promoCodesValidatePromoCodeRaw(requestParameters: PromoCodesValidatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Validate a promo code without applying it. Anyone can validate to see if code is valid.
     * Validate Promo Code
     */
    promoCodesValidatePromoCode(requestParameters: PromoCodesValidatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class PromoCodesApi extends runtime.BaseAPI implements PromoCodesApiInterface {

    /**
     * Apply a promo code to get special SMS pricing. This updates the user\'s sms_cost permanently (or until another promo is applied).
     * Apply Promo Code
     */
    async promoCodesApplyPromoCodeRaw(requestParameters: PromoCodesApplyPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplyPromoCodeResponse>> {
        if (requestParameters['applyPromoCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'applyPromoCodeRequest',
                'Required parameter "applyPromoCodeRequest" was null or undefined when calling promoCodesApplyPromoCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/apply`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplyPromoCodeRequestToJSON(requestParameters['applyPromoCodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplyPromoCodeResponseFromJSON(jsonValue));
    }

    /**
     * Apply a promo code to get special SMS pricing. This updates the user\'s sms_cost permanently (or until another promo is applied).
     * Apply Promo Code
     */
    async promoCodesApplyPromoCode(requestParameters: PromoCodesApplyPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplyPromoCodeResponse> {
        const response = await this.promoCodesApplyPromoCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new promo code with special SMS pricing. (Admin only)
     * Create Promo Code
     */
    async promoCodesCreatePromoCodeRaw(requestParameters: PromoCodesCreatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoCodePublic>> {
        if (requestParameters['promoCodeCreate'] == null) {
            throw new runtime.RequiredError(
                'promoCodeCreate',
                'Required parameter "promoCodeCreate" was null or undefined when calling promoCodesCreatePromoCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PromoCodeCreateToJSON(requestParameters['promoCodeCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromoCodePublicFromJSON(jsonValue));
    }

    /**
     * Create a new promo code with special SMS pricing. (Admin only)
     * Create Promo Code
     */
    async promoCodesCreatePromoCode(requestParameters: PromoCodesCreatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoCodePublic> {
        const response = await this.promoCodesCreatePromoCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a promo code. (Admin only)
     * Delete Promo Code
     */
    async promoCodesDeletePromoCodeRaw(requestParameters: PromoCodesDeletePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        if (requestParameters['promoId'] == null) {
            throw new runtime.RequiredError(
                'promoId',
                'Required parameter "promoId" was null or undefined when calling promoCodesDeletePromoCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/{promo_id}`;
        urlPath = urlPath.replace(`{${"promo_id"}}`, encodeURIComponent(String(requestParameters['promoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Delete a promo code. (Admin only)
     * Delete Promo Code
     */
    async promoCodesDeletePromoCode(requestParameters: PromoCodesDeletePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.promoCodesDeletePromoCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all promo codes. (Admin only)
     * Get All Promo Codes
     */
    async promoCodesGetAllPromoCodesRaw(requestParameters: PromoCodesGetAllPromoCodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoCodesPublic>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['activeOnly'] != null) {
            queryParameters['active_only'] = requestParameters['activeOnly'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromoCodesPublicFromJSON(jsonValue));
    }

    /**
     * Get all promo codes. (Admin only)
     * Get All Promo Codes
     */
    async promoCodesGetAllPromoCodes(requestParameters: PromoCodesGetAllPromoCodesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoCodesPublic> {
        const response = await this.promoCodesGetAllPromoCodesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check if current user has a special promo rate applied.
     * Get My Active Promo
     */
    async promoCodesGetMyActivePromoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/my/active`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Check if current user has a special promo rate applied.
     * Get My Active Promo
     */
    async promoCodesGetMyActivePromo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.promoCodesGetMyActivePromoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a specific promo code by code. (Admin only)
     * Get Promo Code
     */
    async promoCodesGetPromoCodeRaw(requestParameters: PromoCodesGetPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoCodePublic>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling promoCodesGetPromoCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/{code}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromoCodePublicFromJSON(jsonValue));
    }

    /**
     * Get a specific promo code by code. (Admin only)
     * Get Promo Code
     */
    async promoCodesGetPromoCode(requestParameters: PromoCodesGetPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoCodePublic> {
        const response = await this.promoCodesGetPromoCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get usage statistics for a promo code. (Admin only)
     * Get Promo Code Stats
     */
    async promoCodesGetPromoCodeStatsRaw(requestParameters: PromoCodesGetPromoCodeStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['promoId'] == null) {
            throw new runtime.RequiredError(
                'promoId',
                'Required parameter "promoId" was null or undefined when calling promoCodesGetPromoCodeStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/{promo_id}/stats`;
        urlPath = urlPath.replace(`{${"promo_id"}}`, encodeURIComponent(String(requestParameters['promoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get usage statistics for a promo code. (Admin only)
     * Get Promo Code Stats
     */
    async promoCodesGetPromoCodeStats(requestParameters: PromoCodesGetPromoCodeStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.promoCodesGetPromoCodeStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a promo code. (Admin only)
     * Update Promo Code
     */
    async promoCodesUpdatePromoCodeRaw(requestParameters: PromoCodesUpdatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoCodePublic>> {
        if (requestParameters['promoId'] == null) {
            throw new runtime.RequiredError(
                'promoId',
                'Required parameter "promoId" was null or undefined when calling promoCodesUpdatePromoCode().'
            );
        }

        if (requestParameters['promoCodeUpdate'] == null) {
            throw new runtime.RequiredError(
                'promoCodeUpdate',
                'Required parameter "promoCodeUpdate" was null or undefined when calling promoCodesUpdatePromoCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/{promo_id}`;
        urlPath = urlPath.replace(`{${"promo_id"}}`, encodeURIComponent(String(requestParameters['promoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PromoCodeUpdateToJSON(requestParameters['promoCodeUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromoCodePublicFromJSON(jsonValue));
    }

    /**
     * Update a promo code. (Admin only)
     * Update Promo Code
     */
    async promoCodesUpdatePromoCode(requestParameters: PromoCodesUpdatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoCodePublic> {
        const response = await this.promoCodesUpdatePromoCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validate a promo code without applying it. Anyone can validate to see if code is valid.
     * Validate Promo Code
     */
    async promoCodesValidatePromoCodeRaw(requestParameters: PromoCodesValidatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling promoCodesValidatePromoCode().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/promo-codes/validate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Validate a promo code without applying it. Anyone can validate to see if code is valid.
     * Validate Promo Code
     */
    async promoCodesValidatePromoCode(requestParameters: PromoCodesValidatePromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.promoCodesValidatePromoCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
