/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SendSMSRequest,
  SendSMSResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SendSMSRequestFromJSON,
    SendSMSRequestToJSON,
    SendSMSResponseFromJSON,
    SendSMSResponseToJSON,
} from '../models/index';

export interface SmsDeliveryReportWebhookRequest {
    requestBody: { [key: string]: any; };
}

export interface SmsSendSmsRequest {
    sendSMSRequest: SendSMSRequest;
}

/**
 * SmsApi - interface
 * 
 * @export
 * @interface SmsApiInterface
 */
export interface SmsApiInterface {
    /**
     * Set this URL in Africa\'s Talking dashboard: https://yourdomain.com/api/v1/sms/webhook/delivery-reports
     * @summary Delivery Report Webhook
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SmsApiInterface
     */
    smsDeliveryReportWebhookRaw(requestParameters: SmsDeliveryReportWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Set this URL in Africa\'s Talking dashboard: https://yourdomain.com/api/v1/sms/webhook/delivery-reports
     * Delivery Report Webhook
     */
    smsDeliveryReportWebhook(requestParameters: SmsDeliveryReportWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Send SMS with: - Wallet deduction - Transaction + SMS history logging - Template support - Real-time delivery via WebSocket - No Celery needed
     * @summary Send Sms
     * @param {SendSMSRequest} sendSMSRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SmsApiInterface
     */
    smsSendSmsRaw(requestParameters: SmsSendSmsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendSMSResponse>>;

    /**
     * Send SMS with: - Wallet deduction - Transaction + SMS history logging - Template support - Real-time delivery via WebSocket - No Celery needed
     * Send Sms
     */
    smsSendSms(requestParameters: SmsSendSmsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendSMSResponse>;

}

/**
 * 
 */
export class SmsApi extends runtime.BaseAPI implements SmsApiInterface {

    /**
     * Set this URL in Africa\'s Talking dashboard: https://yourdomain.com/api/v1/sms/webhook/delivery-reports
     * Delivery Report Webhook
     */
    async smsDeliveryReportWebhookRaw(requestParameters: SmsDeliveryReportWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling smsDeliveryReportWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/sms/webhook/delivery-reports`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Set this URL in Africa\'s Talking dashboard: https://yourdomain.com/api/v1/sms/webhook/delivery-reports
     * Delivery Report Webhook
     */
    async smsDeliveryReportWebhook(requestParameters: SmsDeliveryReportWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.smsDeliveryReportWebhookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send SMS with: - Wallet deduction - Transaction + SMS history logging - Template support - Real-time delivery via WebSocket - No Celery needed
     * Send Sms
     */
    async smsSendSmsRaw(requestParameters: SmsSendSmsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendSMSResponse>> {
        if (requestParameters['sendSMSRequest'] == null) {
            throw new runtime.RequiredError(
                'sendSMSRequest',
                'Required parameter "sendSMSRequest" was null or undefined when calling smsSendSms().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/sms/send`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendSMSRequestToJSON(requestParameters['sendSMSRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendSMSResponseFromJSON(jsonValue));
    }

    /**
     * Send SMS with: - Wallet deduction - Transaction + SMS history logging - Template support - Real-time delivery via WebSocket - No Celery needed
     * Send Sms
     */
    async smsSendSms(requestParameters: SmsSendSmsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendSMSResponse> {
        const response = await this.smsSendSmsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
