/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Message,
  TemplateCreate,
  TemplatePublic,
  TemplateUpdate,
  TemplatesPublic,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageFromJSON,
    MessageToJSON,
    TemplateCreateFromJSON,
    TemplateCreateToJSON,
    TemplatePublicFromJSON,
    TemplatePublicToJSON,
    TemplateUpdateFromJSON,
    TemplateUpdateToJSON,
    TemplatesPublicFromJSON,
    TemplatesPublicToJSON,
} from '../models/index';

export interface TemplatesCreateTemplateRequest {
    templateCreate: TemplateCreate;
}

export interface TemplatesDeleteTemplateRequest {
    id: string;
}

export interface TemplatesReadDefaultTemplatesRequest {
    skip?: number;
    limit?: number;
}

export interface TemplatesReadTemplateRequest {
    id: string;
}

export interface TemplatesReadTemplatesRequest {
    skip?: number;
    limit?: number;
    tag?: string | null;
    defaultOnly?: boolean;
}

export interface TemplatesReadTemplatesByTagRequest {
    tag: string;
    skip?: number;
    limit?: number;
}

export interface TemplatesSetTemplateAsDefaultRequest {
    id: string;
}

export interface TemplatesUnsetTemplateAsDefaultRequest {
    id: string;
}

export interface TemplatesUpdateTemplateRequest {
    id: string;
    templateUpdate: TemplateUpdate;
}

/**
 * TemplatesApi - interface
 * 
 * @export
 * @interface TemplatesApiInterface
 */
export interface TemplatesApiInterface {
    /**
     * Create new template.  Templates can be used to store frequently used SMS messages.
     * @summary Create Template
     * @param {TemplateCreate} templateCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesCreateTemplateRaw(requestParameters: TemplatesCreateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>>;

    /**
     * Create new template.  Templates can be used to store frequently used SMS messages.
     * Create Template
     */
    templatesCreateTemplate(requestParameters: TemplatesCreateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic>;

    /**
     * Delete a template.
     * @summary Delete Template
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesDeleteTemplateRaw(requestParameters: TemplatesDeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>>;

    /**
     * Delete a template.
     * Delete Template
     */
    templatesDeleteTemplate(requestParameters: TemplatesDeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message>;

    /**
     * Get all unique template tags for the current user.  Useful for filtering and organizing templates.
     * @summary Get Template Tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesGetTemplateTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string | null>>>;

    /**
     * Get all unique template tags for the current user.  Useful for filtering and organizing templates.
     * Get Template Tags
     */
    templatesGetTemplateTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string | null>>;

    /**
     * Get all default templates for the current user.  Default templates are pre-configured templates that users frequently use.
     * @summary Read Default Templates
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesReadDefaultTemplatesRaw(requestParameters: TemplatesReadDefaultTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPublic>>;

    /**
     * Get all default templates for the current user.  Default templates are pre-configured templates that users frequently use.
     * Read Default Templates
     */
    templatesReadDefaultTemplates(requestParameters: TemplatesReadDefaultTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPublic>;

    /**
     * Get template by ID.
     * @summary Read Template
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesReadTemplateRaw(requestParameters: TemplatesReadTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>>;

    /**
     * Get template by ID.
     * Read Template
     */
    templatesReadTemplate(requestParameters: TemplatesReadTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic>;

    /**
     * Retrieve templates.  - **skip**: Number of records to skip (pagination) - **limit**: Maximum number of records to return - **tag**: Filter by template tag (e.g., \'custom\', \'marketing\', \'notification\') - **default_only**: If true, return only default templates
     * @summary Read Templates
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {string} [tag] Filter templates by tag
     * @param {boolean} [defaultOnly] Return only default templates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesReadTemplatesRaw(requestParameters: TemplatesReadTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPublic>>;

    /**
     * Retrieve templates.  - **skip**: Number of records to skip (pagination) - **limit**: Maximum number of records to return - **tag**: Filter by template tag (e.g., \'custom\', \'marketing\', \'notification\') - **default_only**: If true, return only default templates
     * Read Templates
     */
    templatesReadTemplates(requestParameters: TemplatesReadTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPublic>;

    /**
     * Get templates by tag.  Useful for grouping templates by categories like: - \'marketing\': Marketing campaign templates - \'notification\': System notification templates - \'alert\': Alert message templates - \'custom\': User-created custom templates
     * @summary Read Templates By Tag
     * @param {string} tag 
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesReadTemplatesByTagRaw(requestParameters: TemplatesReadTemplatesByTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPublic>>;

    /**
     * Get templates by tag.  Useful for grouping templates by categories like: - \'marketing\': Marketing campaign templates - \'notification\': System notification templates - \'alert\': Alert message templates - \'custom\': User-created custom templates
     * Read Templates By Tag
     */
    templatesReadTemplatesByTag(requestParameters: TemplatesReadTemplatesByTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPublic>;

    /**
     * Set a template as the default template.  This will unset any existing default template automatically.
     * @summary Set Template As Default
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesSetTemplateAsDefaultRaw(requestParameters: TemplatesSetTemplateAsDefaultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>>;

    /**
     * Set a template as the default template.  This will unset any existing default template automatically.
     * Set Template As Default
     */
    templatesSetTemplateAsDefault(requestParameters: TemplatesSetTemplateAsDefaultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic>;

    /**
     * Unset a template as the default template.
     * @summary Unset Template As Default
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesUnsetTemplateAsDefaultRaw(requestParameters: TemplatesUnsetTemplateAsDefaultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>>;

    /**
     * Unset a template as the default template.
     * Unset Template As Default
     */
    templatesUnsetTemplateAsDefault(requestParameters: TemplatesUnsetTemplateAsDefaultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic>;

    /**
     * Update a template.
     * @summary Update Template
     * @param {string} id 
     * @param {TemplateUpdate} templateUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesUpdateTemplateRaw(requestParameters: TemplatesUpdateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>>;

    /**
     * Update a template.
     * Update Template
     */
    templatesUpdateTemplate(requestParameters: TemplatesUpdateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic>;

}

/**
 * 
 */
export class TemplatesApi extends runtime.BaseAPI implements TemplatesApiInterface {

    /**
     * Create new template.  Templates can be used to store frequently used SMS messages.
     * Create Template
     */
    async templatesCreateTemplateRaw(requestParameters: TemplatesCreateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>> {
        if (requestParameters['templateCreate'] == null) {
            throw new runtime.RequiredError(
                'templateCreate',
                'Required parameter "templateCreate" was null or undefined when calling templatesCreateTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateCreateToJSON(requestParameters['templateCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatePublicFromJSON(jsonValue));
    }

    /**
     * Create new template.  Templates can be used to store frequently used SMS messages.
     * Create Template
     */
    async templatesCreateTemplate(requestParameters: TemplatesCreateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic> {
        const response = await this.templatesCreateTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a template.
     * Delete Template
     */
    async templatesDeleteTemplateRaw(requestParameters: TemplatesDeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling templatesDeleteTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Delete a template.
     * Delete Template
     */
    async templatesDeleteTemplate(requestParameters: TemplatesDeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.templatesDeleteTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all unique template tags for the current user.  Useful for filtering and organizing templates.
     * Get Template Tags
     */
    async templatesGetTemplateTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string | null>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/tags/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all unique template tags for the current user.  Useful for filtering and organizing templates.
     * Get Template Tags
     */
    async templatesGetTemplateTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string | null>> {
        const response = await this.templatesGetTemplateTagsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all default templates for the current user.  Default templates are pre-configured templates that users frequently use.
     * Read Default Templates
     */
    async templatesReadDefaultTemplatesRaw(requestParameters: TemplatesReadDefaultTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPublic>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/defaults/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesPublicFromJSON(jsonValue));
    }

    /**
     * Get all default templates for the current user.  Default templates are pre-configured templates that users frequently use.
     * Read Default Templates
     */
    async templatesReadDefaultTemplates(requestParameters: TemplatesReadDefaultTemplatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPublic> {
        const response = await this.templatesReadDefaultTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get template by ID.
     * Read Template
     */
    async templatesReadTemplateRaw(requestParameters: TemplatesReadTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling templatesReadTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatePublicFromJSON(jsonValue));
    }

    /**
     * Get template by ID.
     * Read Template
     */
    async templatesReadTemplate(requestParameters: TemplatesReadTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic> {
        const response = await this.templatesReadTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve templates.  - **skip**: Number of records to skip (pagination) - **limit**: Maximum number of records to return - **tag**: Filter by template tag (e.g., \'custom\', \'marketing\', \'notification\') - **default_only**: If true, return only default templates
     * Read Templates
     */
    async templatesReadTemplatesRaw(requestParameters: TemplatesReadTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPublic>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['defaultOnly'] != null) {
            queryParameters['default_only'] = requestParameters['defaultOnly'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesPublicFromJSON(jsonValue));
    }

    /**
     * Retrieve templates.  - **skip**: Number of records to skip (pagination) - **limit**: Maximum number of records to return - **tag**: Filter by template tag (e.g., \'custom\', \'marketing\', \'notification\') - **default_only**: If true, return only default templates
     * Read Templates
     */
    async templatesReadTemplates(requestParameters: TemplatesReadTemplatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPublic> {
        const response = await this.templatesReadTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get templates by tag.  Useful for grouping templates by categories like: - \'marketing\': Marketing campaign templates - \'notification\': System notification templates - \'alert\': Alert message templates - \'custom\': User-created custom templates
     * Read Templates By Tag
     */
    async templatesReadTemplatesByTagRaw(requestParameters: TemplatesReadTemplatesByTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPublic>> {
        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling templatesReadTemplatesByTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/by-tag/{tag}`;
        urlPath = urlPath.replace(`{${"tag"}}`, encodeURIComponent(String(requestParameters['tag'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesPublicFromJSON(jsonValue));
    }

    /**
     * Get templates by tag.  Useful for grouping templates by categories like: - \'marketing\': Marketing campaign templates - \'notification\': System notification templates - \'alert\': Alert message templates - \'custom\': User-created custom templates
     * Read Templates By Tag
     */
    async templatesReadTemplatesByTag(requestParameters: TemplatesReadTemplatesByTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPublic> {
        const response = await this.templatesReadTemplatesByTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set a template as the default template.  This will unset any existing default template automatically.
     * Set Template As Default
     */
    async templatesSetTemplateAsDefaultRaw(requestParameters: TemplatesSetTemplateAsDefaultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling templatesSetTemplateAsDefault().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/{id}/set-default`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatePublicFromJSON(jsonValue));
    }

    /**
     * Set a template as the default template.  This will unset any existing default template automatically.
     * Set Template As Default
     */
    async templatesSetTemplateAsDefault(requestParameters: TemplatesSetTemplateAsDefaultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic> {
        const response = await this.templatesSetTemplateAsDefaultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unset a template as the default template.
     * Unset Template As Default
     */
    async templatesUnsetTemplateAsDefaultRaw(requestParameters: TemplatesUnsetTemplateAsDefaultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling templatesUnsetTemplateAsDefault().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/{id}/unset-default`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatePublicFromJSON(jsonValue));
    }

    /**
     * Unset a template as the default template.
     * Unset Template As Default
     */
    async templatesUnsetTemplateAsDefault(requestParameters: TemplatesUnsetTemplateAsDefaultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic> {
        const response = await this.templatesUnsetTemplateAsDefaultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a template.
     * Update Template
     */
    async templatesUpdateTemplateRaw(requestParameters: TemplatesUpdateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatePublic>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling templatesUpdateTemplate().'
            );
        }

        if (requestParameters['templateUpdate'] == null) {
            throw new runtime.RequiredError(
                'templateUpdate',
                'Required parameter "templateUpdate" was null or undefined when calling templatesUpdateTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/templates/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateUpdateToJSON(requestParameters['templateUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatePublicFromJSON(jsonValue));
    }

    /**
     * Update a template.
     * Update Template
     */
    async templatesUpdateTemplate(requestParameters: TemplatesUpdateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatePublic> {
        const response = await this.templatesUpdateTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
