/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Message,
  TransactionCreate,
  TransactionPublic,
  TransactionUpdate,
  TransactionsPublic,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageFromJSON,
    MessageToJSON,
    TransactionCreateFromJSON,
    TransactionCreateToJSON,
    TransactionPublicFromJSON,
    TransactionPublicToJSON,
    TransactionUpdateFromJSON,
    TransactionUpdateToJSON,
    TransactionsPublicFromJSON,
    TransactionsPublicToJSON,
} from '../models/index';

export interface TransactionsCreateTransactionRequest {
    transactionCreate: TransactionCreate;
}

export interface TransactionsDeleteTransactionRequest {
    transactionId: string;
}

export interface TransactionsGetTransactionRequest {
    transactionId: string;
}

export interface TransactionsListAllTransactionsRequest {
    skip?: number;
    limit?: number;
    status?: string | null;
    transactionType?: string | null;
}

export interface TransactionsListMyTransactionsRequest {
    skip?: number;
    limit?: number;
    status?: string | null;
    transactionType?: string | null;
}

export interface TransactionsUpdateTransactionRequest {
    transactionId: string;
    transactionUpdate: TransactionUpdate;
}

/**
 * TransactionsApi - interface
 * 
 * @export
 * @interface TransactionsApiInterface
 */
export interface TransactionsApiInterface {
    /**
     * 
     * @summary Create Transaction
     * @param {TransactionCreate} transactionCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    transactionsCreateTransactionRaw(requestParameters: TransactionsCreateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPublic>>;

    /**
     * Create Transaction
     */
    transactionsCreateTransaction(requestParameters: TransactionsCreateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPublic>;

    /**
     * 
     * @summary Delete Transaction
     * @param {string} transactionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    transactionsDeleteTransactionRaw(requestParameters: TransactionsDeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>>;

    /**
     * Delete Transaction
     */
    transactionsDeleteTransaction(requestParameters: TransactionsDeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message>;

    /**
     * 
     * @summary Get Transaction
     * @param {string} transactionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    transactionsGetTransactionRaw(requestParameters: TransactionsGetTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPublic>>;

    /**
     * Get Transaction
     */
    transactionsGetTransaction(requestParameters: TransactionsGetTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPublic>;

    /**
     * 
     * @summary List All Transactions
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {string} [status] 
     * @param {string} [transactionType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    transactionsListAllTransactionsRaw(requestParameters: TransactionsListAllTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsPublic>>;

    /**
     * List All Transactions
     */
    transactionsListAllTransactions(requestParameters: TransactionsListAllTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsPublic>;

    /**
     * 
     * @summary List My Transactions
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {string} [status] 
     * @param {string} [transactionType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    transactionsListMyTransactionsRaw(requestParameters: TransactionsListMyTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsPublic>>;

    /**
     * List My Transactions
     */
    transactionsListMyTransactions(requestParameters: TransactionsListMyTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsPublic>;

    /**
     * 
     * @summary Transaction Stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    transactionsTransactionStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Transaction Stats
     */
    transactionsTransactionStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * 
     * @summary Update Transaction
     * @param {string} transactionId 
     * @param {TransactionUpdate} transactionUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    transactionsUpdateTransactionRaw(requestParameters: TransactionsUpdateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPublic>>;

    /**
     * Update Transaction
     */
    transactionsUpdateTransaction(requestParameters: TransactionsUpdateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPublic>;

}

/**
 * 
 */
export class TransactionsApi extends runtime.BaseAPI implements TransactionsApiInterface {

    /**
     * Create Transaction
     */
    async transactionsCreateTransactionRaw(requestParameters: TransactionsCreateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPublic>> {
        if (requestParameters['transactionCreate'] == null) {
            throw new runtime.RequiredError(
                'transactionCreate',
                'Required parameter "transactionCreate" was null or undefined when calling transactionsCreateTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/transactions/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionCreateToJSON(requestParameters['transactionCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionPublicFromJSON(jsonValue));
    }

    /**
     * Create Transaction
     */
    async transactionsCreateTransaction(requestParameters: TransactionsCreateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPublic> {
        const response = await this.transactionsCreateTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Transaction
     */
    async transactionsDeleteTransactionRaw(requestParameters: TransactionsDeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling transactionsDeleteTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/transactions/{transaction_id}`;
        urlPath = urlPath.replace(`{${"transaction_id"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Delete Transaction
     */
    async transactionsDeleteTransaction(requestParameters: TransactionsDeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.transactionsDeleteTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Transaction
     */
    async transactionsGetTransactionRaw(requestParameters: TransactionsGetTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPublic>> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling transactionsGetTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/transactions/{transaction_id}`;
        urlPath = urlPath.replace(`{${"transaction_id"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionPublicFromJSON(jsonValue));
    }

    /**
     * Get Transaction
     */
    async transactionsGetTransaction(requestParameters: TransactionsGetTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPublic> {
        const response = await this.transactionsGetTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List All Transactions
     */
    async transactionsListAllTransactionsRaw(requestParameters: TransactionsListAllTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsPublic>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['transactionType'] != null) {
            queryParameters['transaction_type'] = requestParameters['transactionType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/transactions/all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsPublicFromJSON(jsonValue));
    }

    /**
     * List All Transactions
     */
    async transactionsListAllTransactions(requestParameters: TransactionsListAllTransactionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsPublic> {
        const response = await this.transactionsListAllTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List My Transactions
     */
    async transactionsListMyTransactionsRaw(requestParameters: TransactionsListMyTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsPublic>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['transactionType'] != null) {
            queryParameters['transaction_type'] = requestParameters['transactionType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/transactions/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsPublicFromJSON(jsonValue));
    }

    /**
     * List My Transactions
     */
    async transactionsListMyTransactions(requestParameters: TransactionsListMyTransactionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsPublic> {
        const response = await this.transactionsListMyTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Transaction Stats
     */
    async transactionsTransactionStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/transactions/stats/summary`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Transaction Stats
     */
    async transactionsTransactionStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.transactionsTransactionStatsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Transaction
     */
    async transactionsUpdateTransactionRaw(requestParameters: TransactionsUpdateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPublic>> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling transactionsUpdateTransaction().'
            );
        }

        if (requestParameters['transactionUpdate'] == null) {
            throw new runtime.RequiredError(
                'transactionUpdate',
                'Required parameter "transactionUpdate" was null or undefined when calling transactionsUpdateTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/transactions/{transaction_id}`;
        urlPath = urlPath.replace(`{${"transaction_id"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionUpdateToJSON(requestParameters['transactionUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionPublicFromJSON(jsonValue));
    }

    /**
     * Update Transaction
     */
    async transactionsUpdateTransaction(requestParameters: TransactionsUpdateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPublic> {
        const response = await this.transactionsUpdateTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
