/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddFundsRequest,
  AllPlansResponse,
  ChangePlanRequest,
  CheckBalanceRequest,
  DeductFundsRequest,
  HTTPValidationError,
  PlanInfo,
  UpgradeRecommendationRequest,
  UserProfileResponse,
  UserStatsResponse,
  WalletResponse,
} from '../models/index';
import {
    AddFundsRequestFromJSON,
    AddFundsRequestToJSON,
    AllPlansResponseFromJSON,
    AllPlansResponseToJSON,
    ChangePlanRequestFromJSON,
    ChangePlanRequestToJSON,
    CheckBalanceRequestFromJSON,
    CheckBalanceRequestToJSON,
    DeductFundsRequestFromJSON,
    DeductFundsRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PlanInfoFromJSON,
    PlanInfoToJSON,
    UpgradeRecommendationRequestFromJSON,
    UpgradeRecommendationRequestToJSON,
    UserProfileResponseFromJSON,
    UserProfileResponseToJSON,
    UserStatsResponseFromJSON,
    UserStatsResponseToJSON,
    WalletResponseFromJSON,
    WalletResponseToJSON,
} from '../models/index';

export interface UserDataAddFundsToWalletRequest {
    addFundsRequest: AddFundsRequest;
}

export interface UserDataAdminAddFundsToWalletRequest {
    userId: string;
    addFundsRequest: AddFundsRequest;
}

export interface UserDataAdminChangePlanRequest {
    userId: string;
    changePlanRequest: ChangePlanRequest;
}

export interface UserDataAdminDeductFundsFromWalletRequest {
    userId: string;
    deductFundsRequest: DeductFundsRequest;
}

export interface UserDataChangePlanRequest {
    changePlanRequest: ChangePlanRequest;
}

export interface UserDataCheckSufficientBalanceRequest {
    checkBalanceRequest: CheckBalanceRequest;
}

export interface UserDataDeductFundsFromWalletRequest {
    deductFundsRequest: DeductFundsRequest;
}

export interface UserDataGetUpgradeRecommendationRequest {
    upgradeRecommendationRequest: UpgradeRecommendationRequest;
}

export interface UserDataVerifyRecipientRequest {
    identifier: string;
}

export interface UserDataShareCreditsRequest {
    recipientIdentifier: string;
    amount: number;
    description?: string;
}

/**
 * UserDataApi - interface
 * 
 * @export
 * @interface UserDataApiInterface
 */
export interface UserDataApiInterface {
    /**
     * Add funds to wallet.  This endpoint should be called after successful payment processing.
     * @summary Add Funds To Wallet
     * @param {AddFundsRequest} addFundsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataAddFundsToWalletRaw(requestParameters: UserDataAddFundsToWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>>;

    /**
     * Add funds to wallet.  This endpoint should be called after successful payment processing.
     * Add Funds To Wallet
     */
    userDataAddFundsToWallet(requestParameters: UserDataAddFundsToWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse>;

    /**
     * Add funds to a specific user\'s wallet. (Admin only)
     * @summary Admin Add Funds To Wallet
     * @param {string} userId 
     * @param {AddFundsRequest} addFundsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataAdminAddFundsToWalletRaw(requestParameters: UserDataAdminAddFundsToWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>>;

    /**
     * Add funds to a specific user\'s wallet. (Admin only)
     * Admin Add Funds To Wallet
     */
    userDataAdminAddFundsToWallet(requestParameters: UserDataAdminAddFundsToWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse>;

    /**
     * Change a specific user\'s subscription plan. (Admin only)
     * @summary Admin Change Plan
     * @param {string} userId 
     * @param {ChangePlanRequest} changePlanRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataAdminChangePlanRaw(requestParameters: UserDataAdminChangePlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileResponse>>;

    /**
     * Change a specific user\'s subscription plan. (Admin only)
     * Admin Change Plan
     */
    userDataAdminChangePlan(requestParameters: UserDataAdminChangePlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileResponse>;

    /**
     * Deduct funds from a specific user\'s wallet. (Admin only)
     * @summary Admin Deduct Funds From Wallet
     * @param {string} userId 
     * @param {DeductFundsRequest} deductFundsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataAdminDeductFundsFromWalletRaw(requestParameters: UserDataAdminDeductFundsFromWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>>;

    /**
     * Deduct funds from a specific user\'s wallet. (Admin only)
     * Admin Deduct Funds From Wallet
     */
    userDataAdminDeductFundsFromWallet(requestParameters: UserDataAdminDeductFundsFromWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse>;

    /**
     * Change user\'s subscription plan.  Changing to a better plan will automatically update the SMS cost to a better rate.
     * @summary Change Plan
     * @param {ChangePlanRequest} changePlanRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataChangePlanRaw(requestParameters: UserDataChangePlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileResponse>>;

    /**
     * Change user\'s subscription plan.  Changing to a better plan will automatically update the SMS cost to a better rate.
     * Change Plan
     */
    userDataChangePlan(requestParameters: UserDataChangePlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileResponse>;

    /**
     * Check if user has sufficient balance to send specified number of SMS.
     * @summary Check Sufficient Balance
     * @param {CheckBalanceRequest} checkBalanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataCheckSufficientBalanceRaw(requestParameters: UserDataCheckSufficientBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Check if user has sufficient balance to send specified number of SMS.
     * Check Sufficient Balance
     */
    userDataCheckSufficientBalance(requestParameters: UserDataCheckSufficientBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Deduct funds from wallet.  This is typically used internally when sending SMS messages.
     * @summary Deduct Funds From Wallet
     * @param {DeductFundsRequest} deductFundsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataDeductFundsFromWalletRaw(requestParameters: UserDataDeductFundsFromWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>>;

    /**
     * Deduct funds from wallet.  This is typically used internally when sending SMS messages.
     * Deduct Funds From Wallet
     */
    userDataDeductFundsFromWallet(requestParameters: UserDataDeductFundsFromWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse>;

    /**
     * Get all available plans with their pricing and features.
     * @summary Get All Plans
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataGetAllPlansRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllPlansResponse>>;

    /**
     * Get all available plans with their pricing and features.
     * Get All Plans
     */
    userDataGetAllPlans(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllPlansResponse>;

    /**
     * Get the current user\'s plan information.
     * @summary Get Current Plan
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataGetCurrentPlanRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlanInfo>>;

    /**
     * Get the current user\'s plan information.
     * Get Current Plan
     */
    userDataGetCurrentPlan(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlanInfo>;

    /**
     * Get current SMS cost per message.
     * @summary Get Sms Cost
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataGetSmsCostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Get current SMS cost per message.
     * Get Sms Cost
     */
    userDataGetSmsCost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Get plan upgrade recommendation based on SMS usage.  Calculates potential savings by upgrading to a better plan.
     * @summary Get Upgrade Recommendation
     * @param {UpgradeRecommendationRequest} upgradeRecommendationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataGetUpgradeRecommendationRaw(requestParameters: UserDataGetUpgradeRecommendationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Get plan upgrade recommendation based on SMS usage.  Calculates potential savings by upgrading to a better plan.
     * Get Upgrade Recommendation
     */
    userDataGetUpgradeRecommendation(requestParameters: UserDataGetUpgradeRecommendationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Get user profile with plan and wallet information.
     * @summary Get User Profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataGetUserProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileResponse>>;

    /**
     * Get user profile with plan and wallet information.
     * Get User Profile
     */
    userDataGetUserProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileResponse>;

    /**
     * Get user statistics including how many SMS messages can be sent with current balance.
     * @summary Get User Stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataGetUserStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserStatsResponse>>;

    /**
     * Get user statistics including how many SMS messages can be sent with current balance.
     * Get User Stats
     */
    userDataGetUserStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserStatsResponse>;

    /**
     * Get current wallet balance.
     * @summary Get Wallet Balance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataGetWalletBalanceRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>>;

    /**
     * Get current wallet balance.
     * Get Wallet Balance
     */
    userDataGetWalletBalance(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse>;

    /**
     * Verify a recipient by email or identifier.
     * @summary Verify Recipient
     * @param {string} identifier 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataVerifyRecipientRaw(requestParameters: UserDataVerifyRecipientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Verify a recipient by email or identifier.
     * Verify Recipient
     */
    userDataVerifyRecipient(requestParameters: UserDataVerifyRecipientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Share credits with another user.
     * @summary Share Credits
     * @param {UserDataShareCreditsRequest} requestParameters 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserDataApiInterface
     */
    userDataShareCreditsRaw(requestParameters: UserDataShareCreditsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Share credits with another user.
     * Share Credits
     */
    userDataShareCredits(requestParameters: UserDataShareCreditsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class UserDataApi extends runtime.BaseAPI implements UserDataApiInterface {

    /**
     * Add funds to wallet.  This endpoint should be called after successful payment processing.
     * Add Funds To Wallet
     */
    async userDataAddFundsToWalletRaw(requestParameters: UserDataAddFundsToWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>> {
        if (requestParameters['addFundsRequest'] == null) {
            throw new runtime.RequiredError(
                'addFundsRequest',
                'Required parameter "addFundsRequest" was null or undefined when calling userDataAddFundsToWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/wallet/add-funds`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddFundsRequestToJSON(requestParameters['addFundsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletResponseFromJSON(jsonValue));
    }

    /**
     * Add funds to wallet.  This endpoint should be called after successful payment processing.
     * Add Funds To Wallet
     */
    async userDataAddFundsToWallet(requestParameters: UserDataAddFundsToWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse> {
        const response = await this.userDataAddFundsToWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add funds to a specific user\'s wallet. (Admin only)
     * Admin Add Funds To Wallet
     */
    async userDataAdminAddFundsToWalletRaw(requestParameters: UserDataAdminAddFundsToWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userDataAdminAddFundsToWallet().'
            );
        }

        if (requestParameters['addFundsRequest'] == null) {
            throw new runtime.RequiredError(
                'addFundsRequest',
                'Required parameter "addFundsRequest" was null or undefined when calling userDataAdminAddFundsToWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/admin/{user_id}/add-funds`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddFundsRequestToJSON(requestParameters['addFundsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletResponseFromJSON(jsonValue));
    }

    /**
     * Add funds to a specific user\'s wallet. (Admin only)
     * Admin Add Funds To Wallet
     */
    async userDataAdminAddFundsToWallet(requestParameters: UserDataAdminAddFundsToWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse> {
        const response = await this.userDataAdminAddFundsToWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change a specific user\'s subscription plan. (Admin only)
     * Admin Change Plan
     */
    async userDataAdminChangePlanRaw(requestParameters: UserDataAdminChangePlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userDataAdminChangePlan().'
            );
        }

        if (requestParameters['changePlanRequest'] == null) {
            throw new runtime.RequiredError(
                'changePlanRequest',
                'Required parameter "changePlanRequest" was null or undefined when calling userDataAdminChangePlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/admin/{user_id}/change-plan`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePlanRequestToJSON(requestParameters['changePlanRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Change a specific user\'s subscription plan. (Admin only)
     * Admin Change Plan
     */
    async userDataAdminChangePlan(requestParameters: UserDataAdminChangePlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileResponse> {
        const response = await this.userDataAdminChangePlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deduct funds from a specific user\'s wallet. (Admin only)
     * Admin Deduct Funds From Wallet
     */
    async userDataAdminDeductFundsFromWalletRaw(requestParameters: UserDataAdminDeductFundsFromWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userDataAdminDeductFundsFromWallet().'
            );
        }

        if (requestParameters['deductFundsRequest'] == null) {
            throw new runtime.RequiredError(
                'deductFundsRequest',
                'Required parameter "deductFundsRequest" was null or undefined when calling userDataAdminDeductFundsFromWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/admin/{user_id}/deduct-funds`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeductFundsRequestToJSON(requestParameters['deductFundsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletResponseFromJSON(jsonValue));
    }

    /**
     * Deduct funds from a specific user\'s wallet. (Admin only)
     * Admin Deduct Funds From Wallet
     */
    async userDataAdminDeductFundsFromWallet(requestParameters: UserDataAdminDeductFundsFromWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse> {
        const response = await this.userDataAdminDeductFundsFromWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change user\'s subscription plan.  Changing to a better plan will automatically update the SMS cost to a better rate.
     * Change Plan
     */
    async userDataChangePlanRaw(requestParameters: UserDataChangePlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileResponse>> {
        if (requestParameters['changePlanRequest'] == null) {
            throw new runtime.RequiredError(
                'changePlanRequest',
                'Required parameter "changePlanRequest" was null or undefined when calling userDataChangePlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/plan/change`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePlanRequestToJSON(requestParameters['changePlanRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Change user\'s subscription plan.  Changing to a better plan will automatically update the SMS cost to a better rate.
     * Change Plan
     */
    async userDataChangePlan(requestParameters: UserDataChangePlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileResponse> {
        const response = await this.userDataChangePlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check if user has sufficient balance to send specified number of SMS.
     * Check Sufficient Balance
     */
    async userDataCheckSufficientBalanceRaw(requestParameters: UserDataCheckSufficientBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['checkBalanceRequest'] == null) {
            throw new runtime.RequiredError(
                'checkBalanceRequest',
                'Required parameter "checkBalanceRequest" was null or undefined when calling userDataCheckSufficientBalance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/wallet/check-balance`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckBalanceRequestToJSON(requestParameters['checkBalanceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Check if user has sufficient balance to send specified number of SMS.
     * Check Sufficient Balance
     */
    async userDataCheckSufficientBalance(requestParameters: UserDataCheckSufficientBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.userDataCheckSufficientBalanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deduct funds from wallet.  This is typically used internally when sending SMS messages.
     * Deduct Funds From Wallet
     */
    async userDataDeductFundsFromWalletRaw(requestParameters: UserDataDeductFundsFromWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>> {
        if (requestParameters['deductFundsRequest'] == null) {
            throw new runtime.RequiredError(
                'deductFundsRequest',
                'Required parameter "deductFundsRequest" was null or undefined when calling userDataDeductFundsFromWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/wallet/deduct-funds`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeductFundsRequestToJSON(requestParameters['deductFundsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletResponseFromJSON(jsonValue));
    }

    /**
     * Deduct funds from wallet.  This is typically used internally when sending SMS messages.
     * Deduct Funds From Wallet
     */
    async userDataDeductFundsFromWallet(requestParameters: UserDataDeductFundsFromWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse> {
        const response = await this.userDataDeductFundsFromWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all available plans with their pricing and features.
     * Get All Plans
     */
    async userDataGetAllPlansRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllPlansResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/plans`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllPlansResponseFromJSON(jsonValue));
    }

    /**
     * Get all available plans with their pricing and features.
     * Get All Plans
     */
    async userDataGetAllPlans(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllPlansResponse> {
        const response = await this.userDataGetAllPlansRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the current user\'s plan information.
     * Get Current Plan
     */
    async userDataGetCurrentPlanRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlanInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/plan/current`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanInfoFromJSON(jsonValue));
    }

    /**
     * Get the current user\'s plan information.
     * Get Current Plan
     */
    async userDataGetCurrentPlan(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlanInfo> {
        const response = await this.userDataGetCurrentPlanRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current SMS cost per message.
     * Get Sms Cost
     */
    async userDataGetSmsCostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/sms-cost`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get current SMS cost per message.
     * Get Sms Cost
     */
    async userDataGetSmsCost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.userDataGetSmsCostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get plan upgrade recommendation based on SMS usage.  Calculates potential savings by upgrading to a better plan.
     * Get Upgrade Recommendation
     */
    async userDataGetUpgradeRecommendationRaw(requestParameters: UserDataGetUpgradeRecommendationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['upgradeRecommendationRequest'] == null) {
            throw new runtime.RequiredError(
                'upgradeRecommendationRequest',
                'Required parameter "upgradeRecommendationRequest" was null or undefined when calling userDataGetUpgradeRecommendation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/plan/upgrade-recommendation`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpgradeRecommendationRequestToJSON(requestParameters['upgradeRecommendationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get plan upgrade recommendation based on SMS usage.  Calculates potential savings by upgrading to a better plan.
     * Get Upgrade Recommendation
     */
    async userDataGetUpgradeRecommendation(requestParameters: UserDataGetUpgradeRecommendationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.userDataGetUpgradeRecommendationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user profile with plan and wallet information.
     * Get User Profile
     */
    async userDataGetUserProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Get user profile with plan and wallet information.
     * Get User Profile
     */
    async userDataGetUserProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileResponse> {
        const response = await this.userDataGetUserProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get user statistics including how many SMS messages can be sent with current balance.
     * Get User Stats
     */
    async userDataGetUserStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserStatsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserStatsResponseFromJSON(jsonValue));
    }

    /**
     * Get user statistics including how many SMS messages can be sent with current balance.
     * Get User Stats
     */
    async userDataGetUserStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserStatsResponse> {
        const response = await this.userDataGetUserStatsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current wallet balance.
     * Get Wallet Balance
     */
    async userDataGetWalletBalanceRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-data/wallet`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletResponseFromJSON(jsonValue));
    }

    /**
     * Get current wallet balance.
     * Get Wallet Balance
     */
    async userDataGetWalletBalance(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponse> {
        const response = await this.userDataGetWalletBalanceRaw(initOverrides);
        return await response.value();
    }

    /**
     * Verify a recipient by email or identifier.
     * Verify Recipient
     */
    async userDataVerifyRecipientRaw(requestParameters: UserDataVerifyRecipientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling userDataVerifyRecipient().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['identifier'] != null) {
            queryParameters['identifier'] = requestParameters['identifier'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        let urlPath = `/api/v1/user-data/wallet/verify-recipient`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Verify a recipient by email or identifier.
     * Verify Recipient
     */
    async userDataVerifyRecipient(requestParameters: UserDataVerifyRecipientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.userDataVerifyRecipientRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Share credits with another user.
     * Share Credits
     */
    async userDataShareCreditsRaw(requestParameters: UserDataShareCreditsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['recipientIdentifier'] == null) {
            throw new runtime.RequiredError(
                'recipientIdentifier',
                'Required parameter "recipientIdentifier" was null or undefined when calling userDataShareCredits().'
            );
        }

        if (requestParameters['amount'] == null) {
            throw new runtime.RequiredError(
                'amount',
                'Required parameter "amount" was null or undefined when calling userDataShareCredits().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        let urlPath = `/api/v1/user-data/wallet/share-credits`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: {
                recipient_identifier: requestParameters['recipientIdentifier'],
                amount: requestParameters['amount'],
                description: requestParameters['description'],
            },
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Share credits with another user.
     * Share Credits
     */
    async userDataShareCredits(requestParameters: UserDataShareCreditsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.userDataShareCreditsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
