/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for adding balance to user account
 * @export
 * @interface AddBalanceRequest
 */
export interface AddBalanceRequest {
    /**
     * 
     * @type {string}
     * @memberof AddBalanceRequest
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof AddBalanceRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof AddBalanceRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBalanceRequest
     */
    paymentMethod?: string;
}

/**
 * Check if a given object implements the AddBalanceRequest interface.
 */
export function instanceOfAddBalanceRequest(value: object): value is AddBalanceRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function AddBalanceRequestFromJSON(json: any): AddBalanceRequest {
    return AddBalanceRequestFromJSONTyped(json, false);
}

export function AddBalanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddBalanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'amount': json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
    };
}

export function AddBalanceRequestToJSON(json: any): AddBalanceRequest {
    return AddBalanceRequestToJSONTyped(json, false);
}

export function AddBalanceRequestToJSONTyped(value?: AddBalanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'amount': value['amount'],
        'description': value['description'],
        'payment_method': value['paymentMethod'],
    };
}

