/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddFundsRequest
 */
export interface AddFundsRequest {
    /**
     * Amount to add to wallet (must be greater than 0)
     * @type {number}
     * @memberof AddFundsRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof AddFundsRequest
     */
    paymentMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddFundsRequest
     */
    referenceNumber?: string | null;
}

/**
 * Check if a given object implements the AddFundsRequest interface.
 */
export function instanceOfAddFundsRequest(value: object): value is AddFundsRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function AddFundsRequestFromJSON(json: any): AddFundsRequest {
    return AddFundsRequestFromJSONTyped(json, false);
}

export function AddFundsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddFundsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'referenceNumber': json['reference_number'] == null ? undefined : json['reference_number'],
    };
}

export function AddFundsRequestToJSON(json: any): AddFundsRequest {
    return AddFundsRequestToJSONTyped(json, false);
}

export function AddFundsRequestToJSONTyped(value?: AddFundsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'payment_method': value['paymentMethod'],
        'reference_number': value['referenceNumber'],
    };
}

