/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanInfo } from './PlanInfo';
import {
    PlanInfoFromJSON,
    PlanInfoFromJSONTyped,
    PlanInfoToJSON,
    PlanInfoToJSONTyped,
} from './PlanInfo';

/**
 * 
 * @export
 * @interface AllPlansResponse
 */
export interface AllPlansResponse {
    /**
     * 
     * @type {{ [key: string]: PlanInfo; }}
     * @memberof AllPlansResponse
     */
    plans: { [key: string]: PlanInfo; };
}

/**
 * Check if a given object implements the AllPlansResponse interface.
 */
export function instanceOfAllPlansResponse(value: object): value is AllPlansResponse {
    if (!('plans' in value) || value['plans'] === undefined) return false;
    return true;
}

export function AllPlansResponseFromJSON(json: any): AllPlansResponse {
    return AllPlansResponseFromJSONTyped(json, false);
}

export function AllPlansResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllPlansResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'plans': (mapValues(json['plans'], PlanInfoFromJSON)),
    };
}

export function AllPlansResponseToJSON(json: any): AllPlansResponse {
    return AllPlansResponseToJSONTyped(json, false);
}

export function AllPlansResponseToJSONTyped(value?: AllPlansResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plans': (mapValues(value['plans'], PlanInfoToJSON)),
    };
}

