/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyUpdate
 */
export interface ApiKeyUpdate {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiKeyUpdate
     */
    isActive?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyUpdate
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyUpdate
     */
    permissions?: string | null;
}

/**
 * Check if a given object implements the ApiKeyUpdate interface.
 */
export function instanceOfApiKeyUpdate(value: object): value is ApiKeyUpdate {
    return true;
}

export function ApiKeyUpdateFromJSON(json: any): ApiKeyUpdate {
    return ApiKeyUpdateFromJSONTyped(json, false);
}

export function ApiKeyUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
    };
}

export function ApiKeyUpdateToJSON(json: any): ApiKeyUpdate {
    return ApiKeyUpdateToJSONTyped(json, false);
}

export function ApiKeyUpdateToJSONTyped(value?: ApiKeyUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'is_active': value['isActive'],
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'permissions': value['permissions'],
    };
}

