/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyPromoCodeRequest
 */
export interface ApplyPromoCodeRequest {
    /**
     * Promo code to apply
     * @type {string}
     * @memberof ApplyPromoCodeRequest
     */
    code: string;
}

/**
 * Check if a given object implements the ApplyPromoCodeRequest interface.
 */
export function instanceOfApplyPromoCodeRequest(value: object): value is ApplyPromoCodeRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ApplyPromoCodeRequestFromJSON(json: any): ApplyPromoCodeRequest {
    return ApplyPromoCodeRequestFromJSONTyped(json, false);
}

export function ApplyPromoCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyPromoCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function ApplyPromoCodeRequestToJSON(json: any): ApplyPromoCodeRequest {
    return ApplyPromoCodeRequestToJSONTyped(json, false);
}

export function ApplyPromoCodeRequestToJSONTyped(value?: ApplyPromoCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

