/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyPromoCodeResponse
 */
export interface ApplyPromoCodeResponse {
    /**
     * 
     * @type {string}
     * @memberof ApplyPromoCodeResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ApplyPromoCodeResponse
     */
    oldSmsCost: string;
    /**
     * 
     * @type {string}
     * @memberof ApplyPromoCodeResponse
     */
    newSmsCost: string;
    /**
     * 
     * @type {number}
     * @memberof ApplyPromoCodeResponse
     */
    savingsPerSms: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApplyPromoCodeResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplyPromoCodeResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ApplyPromoCodeResponse interface.
 */
export function instanceOfApplyPromoCodeResponse(value: object): value is ApplyPromoCodeResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('oldSmsCost' in value) || value['oldSmsCost'] === undefined) return false;
    if (!('newSmsCost' in value) || value['newSmsCost'] === undefined) return false;
    if (!('savingsPerSms' in value) || value['savingsPerSms'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApplyPromoCodeResponseFromJSON(json: any): ApplyPromoCodeResponse {
    return ApplyPromoCodeResponseFromJSONTyped(json, false);
}

export function ApplyPromoCodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyPromoCodeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'oldSmsCost': json['old_sms_cost'],
        'newSmsCost': json['new_sms_cost'],
        'savingsPerSms': json['savings_per_sms'],
        'success': json['success'],
        'message': json['message'],
    };
}

export function ApplyPromoCodeResponseToJSON(json: any): ApplyPromoCodeResponse {
    return ApplyPromoCodeResponseToJSONTyped(json, false);
}

export function ApplyPromoCodeResponseToJSONTyped(value?: ApplyPromoCodeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'old_sms_cost': value['oldSmsCost'],
        'new_sms_cost': value['newSmsCost'],
        'savings_per_sms': value['savingsPerSms'],
        'success': value['success'],
        'message': value['message'],
    };
}

