/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating prebuilt templates
 * @export
 * @interface BulkTemplateCreate
 */
export interface BulkTemplateCreate {
    /**
     * 
     * @type {string}
     * @memberof BulkTemplateCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BulkTemplateCreate
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof BulkTemplateCreate
     */
    tag?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BulkTemplateCreate
     */
    _default?: boolean;
}

/**
 * Check if a given object implements the BulkTemplateCreate interface.
 */
export function instanceOfBulkTemplateCreate(value: object): value is BulkTemplateCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function BulkTemplateCreateFromJSON(json: any): BulkTemplateCreate {
    return BulkTemplateCreateFromJSONTyped(json, false);
}

export function BulkTemplateCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkTemplateCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        '_default': json['default'] == null ? undefined : json['default'],
    };
}

export function BulkTemplateCreateToJSON(json: any): BulkTemplateCreate {
    return BulkTemplateCreateToJSONTyped(json, false);
}

export function BulkTemplateCreateToJSONTyped(value?: BulkTemplateCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'content': value['content'],
        'tag': value['tag'],
        'default': value['_default'],
    };
}

