/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkSmsJobPublic
 */
export interface BulkSmsJobPublic {
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobPublic
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobPublic
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof BulkSmsJobPublic
     */
    totalRecipients: number;
    /**
     * 
     * @type {number}
     * @memberof BulkSmsJobPublic
     */
    processedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkSmsJobPublic
     */
    successfulCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkSmsJobPublic
     */
    failedCount?: number;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobPublic
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof BulkSmsJobPublic
     */
    totalCost?: number;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobPublic
     */
    senderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobPublic
     */
    templateId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobPublic
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof BulkSmsJobPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BulkSmsJobPublic
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BulkSmsJobPublic
     */
    startedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BulkSmsJobPublic
     */
    completedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobPublic
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof BulkSmsJobPublic
     */
    progressPercentage?: number;
}

/**
 * Check if a given object implements the BulkSmsJobPublic interface.
 */
export function instanceOfBulkSmsJobPublic(value: object): value is BulkSmsJobPublic {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('totalRecipients' in value) || value['totalRecipients'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function BulkSmsJobPublicFromJSON(json: any): BulkSmsJobPublic {
    return BulkSmsJobPublicFromJSONTyped(json, false);
}

export function BulkSmsJobPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkSmsJobPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'message': json['message'],
        'totalRecipients': json['total_recipients'],
        'processedCount': json['processed_count'] == null ? undefined : json['processed_count'],
        'successfulCount': json['successful_count'] == null ? undefined : json['successful_count'],
        'failedCount': json['failed_count'] == null ? undefined : json['failed_count'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalCost': json['total_cost'] == null ? undefined : json['total_cost'],
        'senderId': json['sender_id'] == null ? undefined : json['sender_id'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'startedAt': (json['started_at'] == null ? null : new Date(json['started_at'])),
        'completedAt': (json['completed_at'] == null ? null : new Date(json['completed_at'])),
        'userId': json['user_id'],
        'progressPercentage': json['progress_percentage'] == null ? undefined : json['progress_percentage'],
    };
}

export function BulkSmsJobPublicToJSON(json: any): BulkSmsJobPublic {
    return BulkSmsJobPublicToJSONTyped(json, false);
}

export function BulkSmsJobPublicToJSONTyped(value?: BulkSmsJobPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'message': value['message'],
        'total_recipients': value['totalRecipients'],
        'processed_count': value['processedCount'],
        'successful_count': value['successfulCount'],
        'failed_count': value['failedCount'],
        'status': value['status'],
        'total_cost': value['totalCost'],
        'sender_id': value['senderId'],
        'template_id': value['templateId'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'user_id': value['userId'],
        'progress_percentage': value['progressPercentage'],
    };
}

