/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkSmsJobCreate
 */
export interface BulkSmsJobCreate {
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobCreate
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkSmsJobCreate
     */
    recipients: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobCreate
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobCreate
     */
    senderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BulkSmsJobCreate
     */
    templateId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BulkSmsJobCreate
     */
    batchSize?: number;
}

/**
 * Check if a given object implements the BulkSmsJobCreate interface.
 */
export function instanceOfBulkSmsJobCreate(value: object): value is BulkSmsJobCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('recipients' in value) || value['recipients'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function BulkSmsJobCreateFromJSON(json: any): BulkSmsJobCreate {
    return BulkSmsJobCreateFromJSONTyped(json, false);
}

export function BulkSmsJobCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkSmsJobCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'recipients': json['recipients'],
        'message': json['message'],
        'senderId': json['sender_id'] == null ? undefined : json['sender_id'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'batchSize': json['batch_size'] == null ? undefined : json['batch_size'],
    };
}

export function BulkSmsJobCreateToJSON(json: any): BulkSmsJobCreate {
    return BulkSmsJobCreateToJSONTyped(json, false);
}

export function BulkSmsJobCreateToJSONTyped(value?: BulkSmsJobCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'recipients': value['recipients'],
        'message': value['message'],
        'sender_id': value['senderId'],
        'template_id': value['templateId'],
        'batch_size': value['batchSize'],
    };
}

