/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkSmsJobPublic } from './BulkSmsJobPublic';
import {
    BulkSmsJobPublicFromJSON,
    BulkSmsJobPublicFromJSONTyped,
    BulkSmsJobPublicToJSON,
    BulkSmsJobPublicToJSONTyped,
} from './BulkSmsJobPublic';

/**
 * 
 * @export
 * @interface BulkSmsJobsPublic
 */
export interface BulkSmsJobsPublic {
    /**
     * 
     * @type {Array<BulkSmsJobPublic>}
     * @memberof BulkSmsJobsPublic
     */
    data: Array<BulkSmsJobPublic>;
    /**
     * 
     * @type {number}
     * @memberof BulkSmsJobsPublic
     */
    count: number;
}

/**
 * Check if a given object implements the BulkSmsJobsPublic interface.
 */
export function instanceOfBulkSmsJobsPublic(value: object): value is BulkSmsJobsPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function BulkSmsJobsPublicFromJSON(json: any): BulkSmsJobsPublic {
    return BulkSmsJobsPublicFromJSONTyped(json, false);
}

export function BulkSmsJobsPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkSmsJobsPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BulkSmsJobPublicFromJSON)),
        'count': json['count'],
    };
}

export function BulkSmsJobsPublicToJSON(json: any): BulkSmsJobsPublic {
    return BulkSmsJobsPublicToJSONTyped(json, false);
}

export function BulkSmsJobsPublicToJSONTyped(value?: BulkSmsJobsPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(BulkSmsJobPublicToJSON)),
        'count': value['count'],
    };
}

