/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePlanRequest
 */
export interface ChangePlanRequest {
    /**
     * Plan name: Basic, Standard, Premium, or Enterprise
     * @type {string}
     * @memberof ChangePlanRequest
     */
    newPlan: string;
}

/**
 * Check if a given object implements the ChangePlanRequest interface.
 */
export function instanceOfChangePlanRequest(value: object): value is ChangePlanRequest {
    if (!('newPlan' in value) || value['newPlan'] === undefined) return false;
    return true;
}

export function ChangePlanRequestFromJSON(json: any): ChangePlanRequest {
    return ChangePlanRequestFromJSONTyped(json, false);
}

export function ChangePlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPlan': json['new_plan'],
    };
}

export function ChangePlanRequestToJSON(json: any): ChangePlanRequest {
    return ChangePlanRequestToJSONTyped(json, false);
}

export function ChangePlanRequestToJSONTyped(value?: ChangePlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_plan': value['newPlan'],
    };
}

