/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckBalanceRequest
 */
export interface CheckBalanceRequest {
    /**
     * Number of SMS to send
     * @type {number}
     * @memberof CheckBalanceRequest
     */
    smsCount: number;
}

/**
 * Check if a given object implements the CheckBalanceRequest interface.
 */
export function instanceOfCheckBalanceRequest(value: object): value is CheckBalanceRequest {
    if (!('smsCount' in value) || value['smsCount'] === undefined) return false;
    return true;
}

export function CheckBalanceRequestFromJSON(json: any): CheckBalanceRequest {
    return CheckBalanceRequestFromJSONTyped(json, false);
}

export function CheckBalanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckBalanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'smsCount': json['sms_count'],
    };
}

export function CheckBalanceRequestToJSON(json: any): CheckBalanceRequest {
    return CheckBalanceRequestToJSONTyped(json, false);
}

export function CheckBalanceRequestToJSONTyped(value?: CheckBalanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sms_count': value['smsCount'],
    };
}

