/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactGroupPublic } from './ContactGroupPublic';
import {
    ContactGroupPublicFromJSON,
    ContactGroupPublicFromJSONTyped,
    ContactGroupPublicToJSON,
    ContactGroupPublicToJSONTyped,
} from './ContactGroupPublic';

/**
 * 
 * @export
 * @interface ContactGroupsPublic
 */
export interface ContactGroupsPublic {
    /**
     * 
     * @type {Array<ContactGroupPublic>}
     * @memberof ContactGroupsPublic
     */
    data: Array<ContactGroupPublic>;
    /**
     * 
     * @type {number}
     * @memberof ContactGroupsPublic
     */
    count: number;
}

/**
 * Check if a given object implements the ContactGroupsPublic interface.
 */
export function instanceOfContactGroupsPublic(value: object): value is ContactGroupsPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ContactGroupsPublicFromJSON(json: any): ContactGroupsPublic {
    return ContactGroupsPublicFromJSONTyped(json, false);
}

export function ContactGroupsPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactGroupsPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ContactGroupPublicFromJSON)),
        'count': json['count'],
    };
}

export function ContactGroupsPublicToJSON(json: any): ContactGroupsPublic {
    return ContactGroupsPublicToJSONTyped(json, false);
}

export function ContactGroupsPublicToJSONTyped(value?: ContactGroupsPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ContactGroupPublicToJSON)),
        'count': value['count'],
    };
}

