/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactGroupUpdate
 */
export interface ContactGroupUpdate {
    /**
     * 
     * @type {string}
     * @memberof ContactGroupUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactGroupUpdate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ContactGroupUpdate interface.
 */
export function instanceOfContactGroupUpdate(value: object): value is ContactGroupUpdate {
    return true;
}

export function ContactGroupUpdateFromJSON(json: any): ContactGroupUpdate {
    return ContactGroupUpdateFromJSONTyped(json, false);
}

export function ContactGroupUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactGroupUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ContactGroupUpdateToJSON(json: any): ContactGroupUpdate {
    return ContactGroupUpdateToJSONTyped(json, false);
}

export function ContactGroupUpdateToJSONTyped(value?: ContactGroupUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

