/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactPublic } from './ContactPublic';
import {
    ContactPublicFromJSON,
    ContactPublicFromJSONTyped,
    ContactPublicToJSON,
    ContactPublicToJSONTyped,
} from './ContactPublic';

/**
 * 
 * @export
 * @interface ContactsPublic
 */
export interface ContactsPublic {
    /**
     * 
     * @type {Array<ContactPublic>}
     * @memberof ContactsPublic
     */
    data: Array<ContactPublic>;
    /**
     * 
     * @type {number}
     * @memberof ContactsPublic
     */
    count: number;
}

/**
 * Check if a given object implements the ContactsPublic interface.
 */
export function instanceOfContactsPublic(value: object): value is ContactsPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ContactsPublicFromJSON(json: any): ContactsPublic {
    return ContactsPublicFromJSONTyped(json, false);
}

export function ContactsPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactsPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ContactPublicFromJSON)),
        'count': json['count'],
    };
}

export function ContactsPublicToJSON(json: any): ContactsPublic {
    return ContactsPublicToJSONTyped(json, false);
}

export function ContactsPublicToJSONTyped(value?: ContactsPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ContactPublicToJSON)),
        'count': value['count'],
    };
}

