/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactGroupCreate
 */
export interface ContactGroupCreate {
    /**
     * 
     * @type {string}
     * @memberof ContactGroupCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContactGroupCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ContactGroupCreate interface.
 */
export function instanceOfContactGroupCreate(value: object): value is ContactGroupCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ContactGroupCreateFromJSON(json: any): ContactGroupCreate {
    return ContactGroupCreateFromJSONTyped(json, false);
}

export function ContactGroupCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactGroupCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ContactGroupCreateToJSON(json: any): ContactGroupCreate {
    return ContactGroupCreateToJSONTyped(json, false);
}

export function ContactGroupCreateToJSONTyped(value?: ContactGroupCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

