/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactCreate
 */
export interface ContactCreate {
    /**
     * 
     * @type {string}
     * @memberof ContactCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContactCreate
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof ContactCreate
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactCreate
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactCreate
     */
    groupId?: string | null;
}

/**
 * Check if a given object implements the ContactCreate interface.
 */
export function instanceOfContactCreate(value: object): value is ContactCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function ContactCreateFromJSON(json: any): ContactCreate {
    return ContactCreateFromJSONTyped(json, false);
}

export function ContactCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'phone': json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
    };
}

export function ContactCreateToJSON(json: any): ContactCreate {
    return ContactCreateToJSONTyped(json, false);
}

export function ContactCreateToJSONTyped(value?: ContactCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'phone': value['phone'],
        'email': value['email'],
        'notes': value['notes'],
        'group_id': value['groupId'],
    };
}

