/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactPublic
 */
export interface ContactPublic {
    /**
     * 
     * @type {string}
     * @memberof ContactPublic
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContactPublic
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof ContactPublic
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactPublic
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactPublic
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ContactPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ContactPublic
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ContactPublic
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ContactPublic
     */
    groupId: string | null;
}

/**
 * Check if a given object implements the ContactPublic interface.
 */
export function instanceOfContactPublic(value: object): value is ContactPublic {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function ContactPublicFromJSON(json: any): ContactPublic {
    return ContactPublicFromJSONTyped(json, false);
}

export function ContactPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'phone': json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'userId': json['user_id'],
        'groupId': json['group_id'],
    };
}

export function ContactPublicToJSON(json: any): ContactPublic {
    return ContactPublicToJSONTyped(json, false);
}

export function ContactPublicToJSONTyped(value?: ContactPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'phone': value['phone'],
        'email': value['email'],
        'notes': value['notes'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'user_id': value['userId'],
        'group_id': value['groupId'],
    };
}

