/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactUpdate
 */
export interface ContactUpdate {
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    groupId?: string | null;
}

/**
 * Check if a given object implements the ContactUpdate interface.
 */
export function instanceOfContactUpdate(value: object): value is ContactUpdate {
    return true;
}

export function ContactUpdateFromJSON(json: any): ContactUpdate {
    return ContactUpdateFromJSONTyped(json, false);
}

export function ContactUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
    };
}

export function ContactUpdateToJSON(json: any): ContactUpdate {
    return ContactUpdateToJSONTyped(json, false);
}

export function ContactUpdateToJSONTyped(value?: ContactUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'phone': value['phone'],
        'email': value['email'],
        'notes': value['notes'],
        'group_id': value['groupId'],
    };
}

