/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeductFundsRequest
 */
export interface DeductFundsRequest {
    /**
     * Amount to deduct from wallet
     * @type {number}
     * @memberof DeductFundsRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof DeductFundsRequest
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the DeductFundsRequest interface.
 */
export function instanceOfDeductFundsRequest(value: object): value is DeductFundsRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function DeductFundsRequestFromJSON(json: any): DeductFundsRequest {
    return DeductFundsRequestFromJSONTyped(json, false);
}

export function DeductFundsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeductFundsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function DeductFundsRequestToJSON(json: any): DeductFundsRequest {
    return DeductFundsRequestToJSONTyped(json, false);
}

export function DeductFundsRequestToJSONTyped(value?: DeductFundsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'reason': value['reason'],
    };
}

