/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginHistoryPublic } from './LoginHistoryPublic';
import {
    LoginHistoryPublicFromJSON,
    LoginHistoryPublicFromJSONTyped,
    LoginHistoryPublicToJSON,
    LoginHistoryPublicToJSONTyped,
} from './LoginHistoryPublic';

/**
 * 
 * @export
 * @interface LoginHistoryPublicList
 */
export interface LoginHistoryPublicList {
    /**
     * 
     * @type {Array<LoginHistoryPublic>}
     * @memberof LoginHistoryPublicList
     */
    data: Array<LoginHistoryPublic>;
    /**
     * 
     * @type {number}
     * @memberof LoginHistoryPublicList
     */
    count: number;
}

/**
 * Check if a given object implements the LoginHistoryPublicList interface.
 */
export function instanceOfLoginHistoryPublicList(value: object): value is LoginHistoryPublicList {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function LoginHistoryPublicListFromJSON(json: any): LoginHistoryPublicList {
    return LoginHistoryPublicListFromJSONTyped(json, false);
}

export function LoginHistoryPublicListFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginHistoryPublicList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(LoginHistoryPublicFromJSON)),
        'count': json['count'],
    };
}

export function LoginHistoryPublicListToJSON(json: any): LoginHistoryPublicList {
    return LoginHistoryPublicListToJSONTyped(json, false);
}

export function LoginHistoryPublicListToJSONTyped(value?: LoginHistoryPublicList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(LoginHistoryPublicToJSON)),
        'count': value['count'],
    };
}

