/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginHistoryPublic
 */
export interface LoginHistoryPublic {
    /**
     * 
     * @type {string}
     * @memberof LoginHistoryPublic
     */
    userAgent: string;
    /**
     * 
     * @type {string}
     * @memberof LoginHistoryPublic
     */
    ipAddress: string;
    /**
     * 
     * @type {string}
     * @memberof LoginHistoryPublic
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginHistoryPublic
     */
    browser?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginHistoryPublic
     */
    os?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginHistoryPublic
     */
    device?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginHistoryPublic
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof LoginHistoryPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof LoginHistoryPublic
     */
    userId: string;
}

/**
 * Check if a given object implements the LoginHistoryPublic interface.
 */
export function instanceOfLoginHistoryPublic(value: object): value is LoginHistoryPublic {
    if (!('userAgent' in value) || value['userAgent'] === undefined) return false;
    if (!('ipAddress' in value) || value['ipAddress'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function LoginHistoryPublicFromJSON(json: any): LoginHistoryPublic {
    return LoginHistoryPublicFromJSONTyped(json, false);
}

export function LoginHistoryPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginHistoryPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'userAgent': json['user_agent'],
        'ipAddress': json['ip_address'],
        'location': json['location'] == null ? undefined : json['location'],
        'browser': json['browser'] == null ? undefined : json['browser'],
        'os': json['os'] == null ? undefined : json['os'],
        'device': json['device'] == null ? undefined : json['device'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'userId': json['user_id'],
    };
}

export function LoginHistoryPublicToJSON(json: any): LoginHistoryPublic {
    return LoginHistoryPublicToJSONTyped(json, false);
}

export function LoginHistoryPublicToJSONTyped(value?: LoginHistoryPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_agent': value['userAgent'],
        'ip_address': value['ipAddress'],
        'location': value['location'],
        'browser': value['browser'],
        'os': value['os'],
        'device': value['device'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'user_id': value['userId'],
    };
}

