/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromoCodePublic } from './PromoCodePublic';
import {
    PromoCodePublicFromJSON,
    PromoCodePublicFromJSONTyped,
    PromoCodePublicToJSON,
    PromoCodePublicToJSONTyped,
} from './PromoCodePublic';

/**
 * 
 * @export
 * @interface PromoCodesPublic
 */
export interface PromoCodesPublic {
    /**
     * 
     * @type {Array<PromoCodePublic>}
     * @memberof PromoCodesPublic
     */
    data: Array<PromoCodePublic>;
    /**
     * 
     * @type {number}
     * @memberof PromoCodesPublic
     */
    count: number;
}

/**
 * Check if a given object implements the PromoCodesPublic interface.
 */
export function instanceOfPromoCodesPublic(value: object): value is PromoCodesPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PromoCodesPublicFromJSON(json: any): PromoCodesPublic {
    return PromoCodesPublicFromJSONTyped(json, false);
}

export function PromoCodesPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromoCodesPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PromoCodePublicFromJSON)),
        'count': json['count'],
    };
}

export function PromoCodesPublicToJSON(json: any): PromoCodesPublic {
    return PromoCodesPublicToJSONTyped(json, false);
}

export function PromoCodesPublicToJSONTyped(value?: PromoCodesPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PromoCodePublicToJSON)),
        'count': value['count'],
    };
}

