/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendSMSRequest
 */
export interface SendSMSRequest {
    /**
     * Phone numbers in international format
     * @type {Array<string>}
     * @memberof SendSMSRequest
     */
    to: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SendSMSRequest
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof SendSMSRequest
     */
    from?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendSMSRequest
     */
    templateId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SendSMSRequest
     */
    enqueue?: boolean;
}

/**
 * Check if a given object implements the SendSMSRequest interface.
 */
export function instanceOfSendSMSRequest(value: object): value is SendSMSRequest {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SendSMSRequestFromJSON(json: any): SendSMSRequest {
    return SendSMSRequestFromJSONTyped(json, false);
}

export function SendSMSRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendSMSRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'message': json['message'],
        'from': json['from'] == null ? undefined : json['from'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'enqueue': json['enqueue'] == null ? undefined : json['enqueue'],
    };
}

export function SendSMSRequestToJSON(json: any): SendSMSRequest {
    return SendSMSRequestToJSONTyped(json, false);
}

export function SendSMSRequestToJSONTyped(value?: SendSMSRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'message': value['message'],
        'from': value['from'],
        'template_id': value['templateId'],
        'enqueue': value['enqueue'],
    };
}

