/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsHistoryUpdate
 */
export interface SmsHistoryUpdate {
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryUpdate
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryUpdate
     */
    deliveryStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryUpdate
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryUpdate
     */
    externalId?: string | null;
}

/**
 * Check if a given object implements the SmsHistoryUpdate interface.
 */
export function instanceOfSmsHistoryUpdate(value: object): value is SmsHistoryUpdate {
    return true;
}

export function SmsHistoryUpdateFromJSON(json: any): SmsHistoryUpdate {
    return SmsHistoryUpdateFromJSONTyped(json, false);
}

export function SmsHistoryUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsHistoryUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'deliveryStatus': json['delivery_status'] == null ? undefined : json['delivery_status'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
    };
}

export function SmsHistoryUpdateToJSON(json: any): SmsHistoryUpdate {
    return SmsHistoryUpdateToJSONTyped(json, false);
}

export function SmsHistoryUpdateToJSONTyped(value?: SmsHistoryUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'delivery_status': value['deliveryStatus'],
        'error_message': value['errorMessage'],
        'external_id': value['externalId'],
    };
}

