/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SmsHistoryPublic } from './SmsHistoryPublic';
import {
    SmsHistoryPublicFromJSON,
    SmsHistoryPublicFromJSONTyped,
    SmsHistoryPublicToJSON,
    SmsHistoryPublicToJSONTyped,
} from './SmsHistoryPublic';

/**
 * 
 * @export
 * @interface SmsHistoriesPublic
 */
export interface SmsHistoriesPublic {
    /**
     * 
     * @type {Array<SmsHistoryPublic>}
     * @memberof SmsHistoriesPublic
     */
    data: Array<SmsHistoryPublic>;
    /**
     * 
     * @type {number}
     * @memberof SmsHistoriesPublic
     */
    count: number;
}

/**
 * Check if a given object implements the SmsHistoriesPublic interface.
 */
export function instanceOfSmsHistoriesPublic(value: object): value is SmsHistoriesPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function SmsHistoriesPublicFromJSON(json: any): SmsHistoriesPublic {
    return SmsHistoriesPublicFromJSONTyped(json, false);
}

export function SmsHistoriesPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsHistoriesPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SmsHistoryPublicFromJSON)),
        'count': json['count'],
    };
}

export function SmsHistoriesPublicToJSON(json: any): SmsHistoriesPublic {
    return SmsHistoriesPublicToJSONTyped(json, false);
}

export function SmsHistoriesPublicToJSONTyped(value?: SmsHistoriesPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(SmsHistoryPublicToJSON)),
        'count': value['count'],
    };
}

