/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsHistoryCreate
 */
export interface SmsHistoryCreate {
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryCreate
     */
    recipient: string;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryCreate
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryCreate
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof SmsHistoryCreate
     */
    smsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SmsHistoryCreate
     */
    cost: number;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryCreate
     */
    templateId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryCreate
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryCreate
     */
    deliveryStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryCreate
     */
    externalId?: string | null;
}

/**
 * Check if a given object implements the SmsHistoryCreate interface.
 */
export function instanceOfSmsHistoryCreate(value: object): value is SmsHistoryCreate {
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    return true;
}

export function SmsHistoryCreateFromJSON(json: any): SmsHistoryCreate {
    return SmsHistoryCreateFromJSONTyped(json, false);
}

export function SmsHistoryCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsHistoryCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'recipient': json['recipient'],
        'message': json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'smsCount': json['sms_count'] == null ? undefined : json['sms_count'],
        'cost': json['cost'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'deliveryStatus': json['delivery_status'] == null ? undefined : json['delivery_status'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
    };
}

export function SmsHistoryCreateToJSON(json: any): SmsHistoryCreate {
    return SmsHistoryCreateToJSONTyped(json, false);
}

export function SmsHistoryCreateToJSONTyped(value?: SmsHistoryCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipient': value['recipient'],
        'message': value['message'],
        'status': value['status'],
        'sms_count': value['smsCount'],
        'cost': value['cost'],
        'template_id': value['templateId'],
        'error_message': value['errorMessage'],
        'delivery_status': value['deliveryStatus'],
        'external_id': value['externalId'],
    };
}

