/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsHistoryPublic
 */
export interface SmsHistoryPublic {
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    recipient: string;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof SmsHistoryPublic
     */
    smsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SmsHistoryPublic
     */
    cost: number;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    templateId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    deliveryStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof SmsHistoryPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SmsHistoryPublic
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SmsHistoryPublic
     */
    sentAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SmsHistoryPublic
     */
    deliveredAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SmsHistoryPublic
     */
    userId: string;
}

/**
 * Check if a given object implements the SmsHistoryPublic interface.
 */
export function instanceOfSmsHistoryPublic(value: object): value is SmsHistoryPublic {
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('sentAt' in value) || value['sentAt'] === undefined) return false;
    if (!('deliveredAt' in value) || value['deliveredAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function SmsHistoryPublicFromJSON(json: any): SmsHistoryPublic {
    return SmsHistoryPublicFromJSONTyped(json, false);
}

export function SmsHistoryPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsHistoryPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'recipient': json['recipient'],
        'message': json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'smsCount': json['sms_count'] == null ? undefined : json['sms_count'],
        'cost': json['cost'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'deliveryStatus': json['delivery_status'] == null ? undefined : json['delivery_status'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'sentAt': (json['sent_at'] == null ? null : new Date(json['sent_at'])),
        'deliveredAt': (json['delivered_at'] == null ? null : new Date(json['delivered_at'])),
        'userId': json['user_id'],
    };
}

export function SmsHistoryPublicToJSON(json: any): SmsHistoryPublic {
    return SmsHistoryPublicToJSONTyped(json, false);
}

export function SmsHistoryPublicToJSONTyped(value?: SmsHistoryPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipient': value['recipient'],
        'message': value['message'],
        'status': value['status'],
        'sms_count': value['smsCount'],
        'cost': value['cost'],
        'template_id': value['templateId'],
        'error_message': value['errorMessage'],
        'delivery_status': value['deliveryStatus'],
        'external_id': value['externalId'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'sent_at': value['sentAt'] == null ? value['sentAt'] : value['sentAt'].toISOString(),
        'delivered_at': value['deliveredAt'] == null ? value['deliveredAt'] : value['deliveredAt'].toISOString(),
        'user_id': value['userId'],
    };
}

