/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * System-wide statistics
 * @export
 * @interface SystemStats
 */
export interface SystemStats {
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    totalUsers: number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    activeUsers: number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    totalTransactions: number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    totalSmsSent: number;
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    totalRevenue: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SystemStats
     */
    usersByPlan: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof SystemStats
     */
    recentSignups: number;
}

/**
 * Check if a given object implements the SystemStats interface.
 */
export function instanceOfSystemStats(value: object): value is SystemStats {
    if (!('totalUsers' in value) || value['totalUsers'] === undefined) return false;
    if (!('activeUsers' in value) || value['activeUsers'] === undefined) return false;
    if (!('totalTransactions' in value) || value['totalTransactions'] === undefined) return false;
    if (!('totalSmsSent' in value) || value['totalSmsSent'] === undefined) return false;
    if (!('totalRevenue' in value) || value['totalRevenue'] === undefined) return false;
    if (!('usersByPlan' in value) || value['usersByPlan'] === undefined) return false;
    if (!('recentSignups' in value) || value['recentSignups'] === undefined) return false;
    return true;
}

export function SystemStatsFromJSON(json: any): SystemStats {
    return SystemStatsFromJSONTyped(json, false);
}

export function SystemStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalUsers': json['total_users'],
        'activeUsers': json['active_users'],
        'totalTransactions': json['total_transactions'],
        'totalSmsSent': json['total_sms_sent'],
        'totalRevenue': json['total_revenue'],
        'usersByPlan': json['users_by_plan'],
        'recentSignups': json['recent_signups'],
    };
}

export function SystemStatsToJSON(json: any): SystemStats {
    return SystemStatsToJSONTyped(json, false);
}

export function SystemStatsToJSONTyped(value?: SystemStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_users': value['totalUsers'],
        'active_users': value['activeUsers'],
        'total_transactions': value['totalTransactions'],
        'total_sms_sent': value['totalSmsSent'],
        'total_revenue': value['totalRevenue'],
        'users_by_plan': value['usersByPlan'],
        'recent_signups': value['recentSignups'],
    };
}

