/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketPublic
 */
export interface TicketPublic {
    /**
     * 
     * @type {string}
     * @memberof TicketPublic
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof TicketPublic
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TicketPublic
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketPublic
     */
    priority?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketPublic
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketPublic
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TicketPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketPublic
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketPublic
     */
    resolvedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TicketPublic
     */
    closedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TicketPublic
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof TicketPublic
     */
    assignedTo: string | null;
    /**
     * 
     * @type {number}
     * @memberof TicketPublic
     */
    responseCount?: number;
}

/**
 * Check if a given object implements the TicketPublic interface.
 */
export function instanceOfTicketPublic(value: object): value is TicketPublic {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('resolvedAt' in value) || value['resolvedAt'] === undefined) return false;
    if (!('closedAt' in value) || value['closedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('assignedTo' in value) || value['assignedTo'] === undefined) return false;
    return true;
}

export function TicketPublicFromJSON(json: any): TicketPublic {
    return TicketPublicFromJSONTyped(json, false);
}

export function TicketPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'description': json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'category': json['category'] == null ? undefined : json['category'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'resolvedAt': (json['resolved_at'] == null ? null : new Date(json['resolved_at'])),
        'closedAt': (json['closed_at'] == null ? null : new Date(json['closed_at'])),
        'userId': json['user_id'],
        'assignedTo': json['assigned_to'],
        'responseCount': json['response_count'] == null ? undefined : json['response_count'],
    };
}

export function TicketPublicToJSON(json: any): TicketPublic {
    return TicketPublicToJSONTyped(json, false);
}

export function TicketPublicToJSONTyped(value?: TicketPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
        'description': value['description'],
        'status': value['status'],
        'priority': value['priority'],
        'category': value['category'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'resolved_at': value['resolvedAt'] == null ? value['resolvedAt'] : value['resolvedAt'].toISOString(),
        'closed_at': value['closedAt'] == null ? value['closedAt'] : value['closedAt'].toISOString(),
        'user_id': value['userId'],
        'assigned_to': value['assignedTo'],
        'response_count': value['responseCount'],
    };
}

