/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketResponsePublic } from './TicketResponsePublic';
import {
    TicketResponsePublicFromJSON,
    TicketResponsePublicFromJSONTyped,
    TicketResponsePublicToJSON,
    TicketResponsePublicToJSONTyped,
} from './TicketResponsePublic';

/**
 * 
 * @export
 * @interface TicketResponsesPublic
 */
export interface TicketResponsesPublic {
    /**
     * 
     * @type {Array<TicketResponsePublic>}
     * @memberof TicketResponsesPublic
     */
    data: Array<TicketResponsePublic>;
    /**
     * 
     * @type {number}
     * @memberof TicketResponsesPublic
     */
    count: number;
}

/**
 * Check if a given object implements the TicketResponsesPublic interface.
 */
export function instanceOfTicketResponsesPublic(value: object): value is TicketResponsesPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function TicketResponsesPublicFromJSON(json: any): TicketResponsesPublic {
    return TicketResponsesPublicFromJSONTyped(json, false);
}

export function TicketResponsesPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketResponsesPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TicketResponsePublicFromJSON)),
        'count': json['count'],
    };
}

export function TicketResponsesPublicToJSON(json: any): TicketResponsesPublic {
    return TicketResponsesPublicToJSONTyped(json, false);
}

export function TicketResponsesPublicToJSONTyped(value?: TicketResponsesPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TicketResponsePublicToJSON)),
        'count': value['count'],
    };
}

