/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketResponseCreate
 */
export interface TicketResponseCreate {
    /**
     * 
     * @type {string}
     * @memberof TicketResponseCreate
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof TicketResponseCreate
     */
    isStaffResponse?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TicketResponseCreate
     */
    ticketId: string;
}

/**
 * Check if a given object implements the TicketResponseCreate interface.
 */
export function instanceOfTicketResponseCreate(value: object): value is TicketResponseCreate {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('ticketId' in value) || value['ticketId'] === undefined) return false;
    return true;
}

export function TicketResponseCreateFromJSON(json: any): TicketResponseCreate {
    return TicketResponseCreateFromJSONTyped(json, false);
}

export function TicketResponseCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketResponseCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'isStaffResponse': json['is_staff_response'] == null ? undefined : json['is_staff_response'],
        'ticketId': json['ticket_id'],
    };
}

export function TicketResponseCreateToJSON(json: any): TicketResponseCreate {
    return TicketResponseCreateToJSONTyped(json, false);
}

export function TicketResponseCreateToJSONTyped(value?: TicketResponseCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'is_staff_response': value['isStaffResponse'],
        'ticket_id': value['ticketId'],
    };
}

