/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketResponsePublic
 */
export interface TicketResponsePublic {
    /**
     * 
     * @type {string}
     * @memberof TicketResponsePublic
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof TicketResponsePublic
     */
    isStaffResponse?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TicketResponsePublic
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TicketResponsePublic
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof TicketResponsePublic
     */
    ticketId: string;
    /**
     * 
     * @type {string}
     * @memberof TicketResponsePublic
     */
    userId: string;
}

/**
 * Check if a given object implements the TicketResponsePublic interface.
 */
export function instanceOfTicketResponsePublic(value: object): value is TicketResponsePublic {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('ticketId' in value) || value['ticketId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function TicketResponsePublicFromJSON(json: any): TicketResponsePublic {
    return TicketResponsePublicFromJSONTyped(json, false);
}

export function TicketResponsePublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketResponsePublic {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'isStaffResponse': json['is_staff_response'] == null ? undefined : json['is_staff_response'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'ticketId': json['ticket_id'],
        'userId': json['user_id'],
    };
}

export function TicketResponsePublicToJSON(json: any): TicketResponsePublic {
    return TicketResponsePublicToJSONTyped(json, false);
}

export function TicketResponsePublicToJSONTyped(value?: TicketResponsePublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'is_staff_response': value['isStaffResponse'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'ticket_id': value['ticketId'],
        'user_id': value['userId'],
    };
}

