/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionPublic } from './TransactionPublic';
import {
    TransactionPublicFromJSON,
    TransactionPublicFromJSONTyped,
    TransactionPublicToJSON,
    TransactionPublicToJSONTyped,
} from './TransactionPublic';

/**
 * 
 * @export
 * @interface TransactionsPublic
 */
export interface TransactionsPublic {
    /**
     * 
     * @type {Array<TransactionPublic>}
     * @memberof TransactionsPublic
     */
    data: Array<TransactionPublic>;
    /**
     * 
     * @type {number}
     * @memberof TransactionsPublic
     */
    count: number;
}

/**
 * Check if a given object implements the TransactionsPublic interface.
 */
export function instanceOfTransactionsPublic(value: object): value is TransactionsPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function TransactionsPublicFromJSON(json: any): TransactionsPublic {
    return TransactionsPublicFromJSONTyped(json, false);
}

export function TransactionsPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TransactionPublicFromJSON)),
        'count': json['count'],
    };
}

export function TransactionsPublicToJSON(json: any): TransactionsPublic {
    return TransactionsPublicToJSONTyped(json, false);
}

export function TransactionsPublicToJSONTyped(value?: TransactionsPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TransactionPublicToJSON)),
        'count': value['count'],
    };
}

