/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionUpdate
 */
export interface TransactionUpdate {
    /**
     * 
     * @type {string}
     * @memberof TransactionUpdate
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionUpdate
     */
    referenceNumber?: string | null;
}

/**
 * Check if a given object implements the TransactionUpdate interface.
 */
export function instanceOfTransactionUpdate(value: object): value is TransactionUpdate {
    return true;
}

export function TransactionUpdateFromJSON(json: any): TransactionUpdate {
    return TransactionUpdateFromJSONTyped(json, false);
}

export function TransactionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'description': json['description'] == null ? undefined : json['description'],
        'referenceNumber': json['reference_number'] == null ? undefined : json['reference_number'],
    };
}

export function TransactionUpdateToJSON(json: any): TransactionUpdate {
    return TransactionUpdateToJSONTyped(json, false);
}

export function TransactionUpdateToJSONTyped(value?: TransactionUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'description': value['description'],
        'reference_number': value['referenceNumber'],
    };
}

