/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionCreate
 */
export interface TransactionCreate {
    /**
     * 
     * @type {string}
     * @memberof TransactionCreate
     */
    transactionType: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionCreate
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionCreate
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionCreate
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCreate
     */
    paymentMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionCreate
     */
    referenceNumber?: string | null;
}

/**
 * Check if a given object implements the TransactionCreate interface.
 */
export function instanceOfTransactionCreate(value: object): value is TransactionCreate {
    if (!('transactionType' in value) || value['transactionType'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function TransactionCreateFromJSON(json: any): TransactionCreate {
    return TransactionCreateFromJSONTyped(json, false);
}

export function TransactionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionType': json['transaction_type'],
        'amount': json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'referenceNumber': json['reference_number'] == null ? undefined : json['reference_number'],
    };
}

export function TransactionCreateToJSON(json: any): TransactionCreate {
    return TransactionCreateToJSONTyped(json, false);
}

export function TransactionCreateToJSONTyped(value?: TransactionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_type': value['transactionType'],
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'status': value['status'],
        'payment_method': value['paymentMethod'],
        'reference_number': value['referenceNumber'],
    };
}

