/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionPublic
 */
export interface TransactionPublic {
    /**
     * 
     * @type {string}
     * @memberof TransactionPublic
     */
    transactionType: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionPublic
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionPublic
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionPublic
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionPublic
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionPublic
     */
    paymentMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionPublic
     */
    referenceNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionPublic
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TransactionPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransactionPublic
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof TransactionPublic
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionPublic
     */
    balanceBefore: number | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionPublic
     */
    balanceAfter: number | null;
}

/**
 * Check if a given object implements the TransactionPublic interface.
 */
export function instanceOfTransactionPublic(value: object): value is TransactionPublic {
    if (!('transactionType' in value) || value['transactionType'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('balanceBefore' in value) || value['balanceBefore'] === undefined) return false;
    if (!('balanceAfter' in value) || value['balanceAfter'] === undefined) return false;
    return true;
}

export function TransactionPublicFromJSON(json: any): TransactionPublic {
    return TransactionPublicFromJSONTyped(json, false);
}

export function TransactionPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionType': json['transaction_type'],
        'amount': json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'referenceNumber': json['reference_number'] == null ? undefined : json['reference_number'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'userId': json['user_id'],
        'balanceBefore': json['balance_before'],
        'balanceAfter': json['balance_after'],
    };
}

export function TransactionPublicToJSON(json: any): TransactionPublic {
    return TransactionPublicToJSONTyped(json, false);
}

export function TransactionPublicToJSONTyped(value?: TransactionPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_type': value['transactionType'],
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'status': value['status'],
        'payment_method': value['paymentMethod'],
        'reference_number': value['referenceNumber'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'user_id': value['userId'],
        'balance_before': value['balanceBefore'],
        'balance_after': value['balanceAfter'],
    };
}

