/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpgradeRecommendationRequest
 */
export interface UpgradeRecommendationRequest {
    /**
     * Estimated monthly SMS volume
     * @type {number}
     * @memberof UpgradeRecommendationRequest
     */
    monthlySmsVolume: number;
}

/**
 * Check if a given object implements the UpgradeRecommendationRequest interface.
 */
export function instanceOfUpgradeRecommendationRequest(value: object): value is UpgradeRecommendationRequest {
    if (!('monthlySmsVolume' in value) || value['monthlySmsVolume'] === undefined) return false;
    return true;
}

export function UpgradeRecommendationRequestFromJSON(json: any): UpgradeRecommendationRequest {
    return UpgradeRecommendationRequestFromJSONTyped(json, false);
}

export function UpgradeRecommendationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpgradeRecommendationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'monthlySmsVolume': json['monthly_sms_volume'],
    };
}

export function UpgradeRecommendationRequestToJSON(json: any): UpgradeRecommendationRequest {
    return UpgradeRecommendationRequestToJSONTyped(json, false);
}

export function UpgradeRecommendationRequestToJSONTyped(value?: UpgradeRecommendationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'monthly_sms_volume': value['monthlySmsVolume'],
    };
}

