/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserStatsResponse
 */
export interface UserStatsResponse {
    /**
     * 
     * @type {string}
     * @memberof UserStatsResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UserStatsResponse
     */
    plan: string;
    /**
     * 
     * @type {string}
     * @memberof UserStatsResponse
     */
    walletBalance: string;
    /**
     * 
     * @type {string}
     * @memberof UserStatsResponse
     */
    smsCost: string;
    /**
     * 
     * @type {number}
     * @memberof UserStatsResponse
     */
    estimatedSmsCount: number;
}

/**
 * Check if a given object implements the UserStatsResponse interface.
 */
export function instanceOfUserStatsResponse(value: object): value is UserStatsResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('plan' in value) || value['plan'] === undefined) return false;
    if (!('walletBalance' in value) || value['walletBalance'] === undefined) return false;
    if (!('smsCost' in value) || value['smsCost'] === undefined) return false;
    if (!('estimatedSmsCount' in value) || value['estimatedSmsCount'] === undefined) return false;
    return true;
}

export function UserStatsResponseFromJSON(json: any): UserStatsResponse {
    return UserStatsResponseFromJSONTyped(json, false);
}

export function UserStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'plan': json['plan'],
        'walletBalance': json['wallet_balance'],
        'smsCost': json['sms_cost'],
        'estimatedSmsCount': json['estimated_sms_count'],
    };
}

export function UserStatsResponseToJSON(json: any): UserStatsResponse {
    return UserStatsResponseToJSONTyped(json, false);
}

export function UserStatsResponseToJSONTyped(value?: UserStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'plan': value['plan'],
        'wallet_balance': value['walletBalance'],
        'sms_cost': value['smsCost'],
        'estimated_sms_count': value['estimatedSmsCount'],
    };
}

