/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileResponse
 */
export interface UserProfileResponse {
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    fullName: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    planSub: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    wallet: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    smsCost: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileResponse
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the UserProfileResponse interface.
 */
export function instanceOfUserProfileResponse(value: object): value is UserProfileResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('planSub' in value) || value['planSub'] === undefined) return false;
    if (!('wallet' in value) || value['wallet'] === undefined) return false;
    if (!('smsCost' in value) || value['smsCost'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function UserProfileResponseFromJSON(json: any): UserProfileResponse {
    return UserProfileResponseFromJSONTyped(json, false);
}

export function UserProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'fullName': json['full_name'],
        'planSub': json['plan_sub'],
        'wallet': json['wallet'],
        'smsCost': json['sms_cost'],
        'isActive': json['is_active'],
    };
}

export function UserProfileResponseToJSON(json: any): UserProfileResponse {
    return UserProfileResponseToJSONTyped(json, false);
}

export function UserProfileResponseToJSONTyped(value?: UserProfileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'full_name': value['fullName'],
        'plan_sub': value['planSub'],
        'wallet': value['wallet'],
        'sms_cost': value['smsCost'],
        'is_active': value['isActive'],
    };
}

