/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPhoneUpdate
 */
export interface UserPhoneUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserPhoneUpdate
     */
    phone: string;
}

/**
 * Check if a given object implements the UserPhoneUpdate interface.
 */
export function instanceOfUserPhoneUpdate(value: object): value is UserPhoneUpdate {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function UserPhoneUpdateFromJSON(json: any): UserPhoneUpdate {
    return UserPhoneUpdateFromJSONTyped(json, false);
}

export function UserPhoneUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPhoneUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
    };
}

export function UserPhoneUpdateToJSON(json: any): UserPhoneUpdate {
    return UserPhoneUpdateToJSONTyped(json, false);
}

export function UserPhoneUpdateToJSONTyped(value?: UserPhoneUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
    };
}

