/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPublic } from './UserPublic';
import {
    UserPublicFromJSON,
    UserPublicFromJSONTyped,
    UserPublicToJSON,
    UserPublicToJSONTyped,
} from './UserPublic';

/**
 * Comprehensive user information with aggregated data
 * @export
 * @interface UserDetailedInfo
 */
export interface UserDetailedInfo {
    /**
     * 
     * @type {UserPublic}
     * @memberof UserDetailedInfo
     */
    user: UserPublic;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    totalTransactions: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    totalTransactionAmount: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    totalSmsSent: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    totalSmsCost: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    totalTemplates: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    totalContacts: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    totalTickets: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    openTickets: number;
    /**
     * 
     * @type {string}
     * @memberof UserDetailedInfo
     */
    recentActivity: string;
    /**
     * 
     * @type {number}
     * @memberof UserDetailedInfo
     */
    accountAgeDays: number;
    /**
     * 
     * @type {Date}
     * @memberof UserDetailedInfo
     */
    lastTransactionDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserDetailedInfo
     */
    lastSmsDate: Date | null;
}

/**
 * Check if a given object implements the UserDetailedInfo interface.
 */
export function instanceOfUserDetailedInfo(value: object): value is UserDetailedInfo {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('totalTransactions' in value) || value['totalTransactions'] === undefined) return false;
    if (!('totalTransactionAmount' in value) || value['totalTransactionAmount'] === undefined) return false;
    if (!('totalSmsSent' in value) || value['totalSmsSent'] === undefined) return false;
    if (!('totalSmsCost' in value) || value['totalSmsCost'] === undefined) return false;
    if (!('totalTemplates' in value) || value['totalTemplates'] === undefined) return false;
    if (!('totalContacts' in value) || value['totalContacts'] === undefined) return false;
    if (!('totalTickets' in value) || value['totalTickets'] === undefined) return false;
    if (!('openTickets' in value) || value['openTickets'] === undefined) return false;
    if (!('recentActivity' in value) || value['recentActivity'] === undefined) return false;
    if (!('accountAgeDays' in value) || value['accountAgeDays'] === undefined) return false;
    if (!('lastTransactionDate' in value) || value['lastTransactionDate'] === undefined) return false;
    if (!('lastSmsDate' in value) || value['lastSmsDate'] === undefined) return false;
    return true;
}

export function UserDetailedInfoFromJSON(json: any): UserDetailedInfo {
    return UserDetailedInfoFromJSONTyped(json, false);
}

export function UserDetailedInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailedInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserPublicFromJSON(json['user']),
        'totalTransactions': json['total_transactions'],
        'totalTransactionAmount': json['total_transaction_amount'],
        'totalSmsSent': json['total_sms_sent'],
        'totalSmsCost': json['total_sms_cost'],
        'totalTemplates': json['total_templates'],
        'totalContacts': json['total_contacts'],
        'totalTickets': json['total_tickets'],
        'openTickets': json['open_tickets'],
        'recentActivity': json['recent_activity'],
        'accountAgeDays': json['account_age_days'],
        'lastTransactionDate': (json['last_transaction_date'] == null ? null : new Date(json['last_transaction_date'])),
        'lastSmsDate': (json['last_sms_date'] == null ? null : new Date(json['last_sms_date'])),
    };
}

export function UserDetailedInfoToJSON(json: any): UserDetailedInfo {
    return UserDetailedInfoToJSONTyped(json, false);
}

export function UserDetailedInfoToJSONTyped(value?: UserDetailedInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserPublicToJSON(value['user']),
        'total_transactions': value['totalTransactions'],
        'total_transaction_amount': value['totalTransactionAmount'],
        'total_sms_sent': value['totalSmsSent'],
        'total_sms_cost': value['totalSmsCost'],
        'total_templates': value['totalTemplates'],
        'total_contacts': value['totalContacts'],
        'total_tickets': value['totalTickets'],
        'open_tickets': value['openTickets'],
        'recent_activity': value['recentActivity'],
        'account_age_days': value['accountAgeDays'],
        'last_transaction_date': value['lastTransactionDate'] == null ? value['lastTransactionDate'] : value['lastTransactionDate'].toISOString(),
        'last_sms_date': value['lastSmsDate'] == null ? value['lastSmsDate'] : value['lastSmsDate'].toISOString(),
    };
}

