/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User search result with key metrics
 * @export
 * @interface UserSearchResult
 */
export interface UserSearchResult {
    /**
     * 
     * @type {string}
     * @memberof UserSearchResult
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserSearchResult
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserSearchResult
     */
    fullName: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserSearchResult
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserSearchResult
     */
    planSub: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserSearchResult
     */
    wallet: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserSearchResult
     */
    totalSmsSent: number;
    /**
     * 
     * @type {number}
     * @memberof UserSearchResult
     */
    totalTransactions: number;
    /**
     * 
     * @type {Date}
     * @memberof UserSearchResult
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the UserSearchResult interface.
 */
export function instanceOfUserSearchResult(value: object): value is UserSearchResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('planSub' in value) || value['planSub'] === undefined) return false;
    if (!('wallet' in value) || value['wallet'] === undefined) return false;
    if (!('totalSmsSent' in value) || value['totalSmsSent'] === undefined) return false;
    if (!('totalTransactions' in value) || value['totalTransactions'] === undefined) return false;
    return true;
}

export function UserSearchResultFromJSON(json: any): UserSearchResult {
    return UserSearchResultFromJSONTyped(json, false);
}

export function UserSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'fullName': json['full_name'],
        'isActive': json['is_active'],
        'planSub': json['plan_sub'],
        'wallet': json['wallet'],
        'totalSmsSent': json['total_sms_sent'],
        'totalTransactions': json['total_transactions'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function UserSearchResultToJSON(json: any): UserSearchResult {
    return UserSearchResultToJSONTyped(json, false);
}

export function UserSearchResultToJSONTyped(value?: UserSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'full_name': value['fullName'],
        'is_active': value['isActive'],
        'plan_sub': value['planSub'],
        'wallet': value['wallet'],
        'total_sms_sent': value['totalSmsSent'],
        'total_transactions': value['totalTransactions'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

