/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPublic
 */
export interface UserPublic {
    /**
     * 
     * @type {string}
     * @memberof UserPublic
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserPublic
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserPublic
     */
    isSuperuser?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserPublic
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPublic
     */
    planSub?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPublic
     */
    wallet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPublic
     */
    smsCost?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPublic
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPublic
     */
    id: string;
}

/**
 * Check if a given object implements the UserPublic interface.
 */
export function instanceOfUserPublic(value: object): value is UserPublic {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserPublicFromJSON(json: any): UserPublic {
    return UserPublicFromJSONTyped(json, false);
}

export function UserPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'isSuperuser': json['is_superuser'] == null ? undefined : json['is_superuser'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'planSub': json['plan_sub'] == null ? undefined : json['plan_sub'],
        'wallet': json['wallet'] == null ? undefined : json['wallet'],
        'smsCost': json['sms_cost'] == null ? undefined : json['sms_cost'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'id': json['id'],
    };
}

export function UserPublicToJSON(json: any): UserPublic {
    return UserPublicToJSONTyped(json, false);
}

export function UserPublicToJSONTyped(value?: UserPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'is_active': value['isActive'],
        'is_superuser': value['isSuperuser'],
        'full_name': value['fullName'],
        'plan_sub': value['planSub'],
        'wallet': value['wallet'],
        'sms_cost': value['smsCost'],
        'phone': value['phone'],
        'id': value['id'],
    };
}

