/* tslint:disable */
/* eslint-disable */
/**
 * LUCO MINTOS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletResponse
 */
export interface WalletResponse {
    /**
     * 
     * @type {string}
     * @memberof WalletResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof WalletResponse
     */
    walletBalance: string;
    /**
     * 
     * @type {string}
     * @memberof WalletResponse
     */
    currency?: string;
}

/**
 * Check if a given object implements the WalletResponse interface.
 */
export function instanceOfWalletResponse(value: object): value is WalletResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('walletBalance' in value) || value['walletBalance'] === undefined) return false;
    return true;
}

export function WalletResponseFromJSON(json: any): WalletResponse {
    return WalletResponseFromJSONTyped(json, false);
}

export function WalletResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'walletBalance': json['wallet_balance'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function WalletResponseToJSON(json: any): WalletResponse {
    return WalletResponseToJSONTyped(json, false);
}

export function WalletResponseToJSONTyped(value?: WalletResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'wallet_balance': value['walletBalance'],
        'currency': value['currency'],
    };
}

